/**
 * DICTION DASH — standalone word-list service.
 *
 * Plain validity/difficulty-tiered word list: common, short, unambiguous words
 * at low tiers, ramping up. Deliberately built as its own module with its own
 * tests (tools/word-gates.mjs) and ZERO runtime dependencies — no runner
 * imports, no external packages — so other games can pull it in unchanged.
 * Every word is hand-curated for this game (a harvested catalog bank was
 * tried in Phase 9 and deliberately removed in Phase 11: curation beats
 * volume now that the no-repeat walk and per-attempt salt carry variety).
 *
 * Determinism contract: every function that makes a choice takes `rand`, a
 * caller-supplied () => float in [0,1). Nothing in here touches Math.random,
 * so a seeded caller always gets the same words.
 *
 * All words are lowercase a–z, no proper nouns, no hyphens or apostrophes.
 */
import { EXTENDED_GUARD } from './guard.js';
import { isBlocked } from './family-blocklist.js';

/**
 * Difficulty tiers, easiest first. Tier 0 is short + high-frequency; later
 * tiers get longer and lean into classically hard spellings, because a fake
 * only creates tension when the real spelling takes a beat to verify.
 */
export const TIERS = [
  // Tier 0 — short, everyday, unambiguous.
  [
    'act', 'add', 'age', 'ago', 'aid', 'aim', 'air', 'all', 'and', 'ant',
    'any', 'apt', 'arc', 'arm', 'art', 'ash', 'ask', 'ate', 'axe', 'bad',
    'bag', 'ban', 'bar', 'bat', 'bay', 'bed', 'bee', 'bet', 'bid', 'big',
    'bin', 'bit', 'bow', 'box', 'boy', 'bud', 'bug', 'bun', 'bus', 'buy',
    'cab', 'can', 'cap', 'car', 'cat', 'cob', 'cod', 'cog', 'cot', 'cow',
    'cry', 'cub', 'cue', 'cup', 'cut', 'dab', 'dam', 'day', 'den', 'dew',
    'dig', 'dim', 'dip', 'dog', 'dot', 'dry', 'dub', 'due', 'dug', 'ear',
    'eat', 'eel', 'egg', 'elf', 'elk', 'elm', 'end', 'era', 'eve', 'ewe',
    'eye', 'fan', 'far', 'fat', 'fed', 'fee', 'few', 'fig', 'fin', 'fit',
    'fix', 'flu', 'fly', 'foe', 'fog', 'for', 'fox', 'fry', 'fun', 'fur',
    'gap', 'gas', 'gel', 'gem', 'get', 'got', 'gum', 'gut', 'guy', 'gym',
    'had', 'ham', 'has', 'hat', 'hay', 'hem', 'hen', 'hid', 'him', 'hip',
    'hit', 'hoe', 'hog', 'hop', 'hot', 'how', 'hub', 'hue', 'hug', 'hum',
    'hut', 'ice', 'icy', 'ill', 'ink', 'inn', 'ion', 'its', 'ivy', 'jab',
    'jam', 'jar', 'jaw', 'jay', 'jet', 'jig', 'job', 'jog', 'jot', 'joy',
    'jug', 'key', 'kid', 'kin', 'kit', 'lab', 'lad', 'lag', 'lap', 'law',
    'lay', 'led', 'leg', 'let', 'lid', 'lie', 'lip', 'lit', 'lob', 'log',
    'lot', 'low', 'mad', 'man', 'map', 'mat', 'may', 'men', 'met', 'mix',
    'mob', 'mop', 'mow', 'mud', 'mug', 'nab', 'nag', 'nap', 'net', 'new',
    'nib', 'nil', 'nip', 'nod', 'nor', 'not', 'now', 'nun', 'nut', 'oak',
    'oar', 'oat', 'odd', 'off', 'oil', 'old', 'one', 'orb', 'ore', 'our',
    'out', 'owe', 'owl', 'own', 'pad', 'pan', 'par', 'pat', 'paw', 'pay',
    'pea', 'peg', 'pen', 'pet', 'pie', 'pig', 'pin', 'pit', 'pod', 'pop',
    'pot', 'pun', 'pup', 'put', 'rag', 'ram', 'ran', 'rap', 'rat', 'raw',
    'ray', 'red', 'rib', 'rid', 'rim', 'rip', 'rob', 'rod', 'rot', 'row',
    'rub', 'rug', 'run', 'rut', 'rye', 'sad', 'sag', 'sap', 'sat', 'saw',
    'say', 'sea', 'see', 'set', 'sew', 'shy', 'sip', 'sir', 'sit', 'six',
    'ski', 'sky', 'sly', 'sob', 'sod', 'son', 'sow', 'soy', 'spa', 'spy',
    'sty', 'sub', 'sue', 'sum', 'sun', 'tab', 'tag', 'tan', 'tap', 'tar',
    'tax', 'tea', 'ten', 'tie', 'tin', 'tip', 'toe', 'ton', 'too', 'top',
    'tow', 'toy', 'try', 'tub', 'tug', 'two', 'urn', 'use', 'van', 'vat',
    'vet', 'vow', 'wad', 'wag', 'war', 'was', 'wax', 'way', 'web', 'wed',
    'wet', 'who', 'why', 'wig', 'win', 'wit', 'woe', 'wok', 'won', 'woo',
    'yak', 'yam', 'yap', 'yes', 'yet', 'yew', 'zap', 'zip', 'zoo',
  ],

  // Tier 1 — common words with one mild spelling decision.
  [
    'able', 'acid', 'apple', 'aunt', 'away', 'baby', 'back', 'bake', 'ball',
    'band', 'bank', 'barn', 'bath', 'beach', 'bead', 'beam', 'bean', 'bear',
    'beat', 'bell', 'belt', 'bend', 'berry', 'best', 'bike', 'bind', 'bird',
    'bite', 'blob', 'blue', 'boat', 'body', 'boil', 'bolt', 'bone', 'book',
    'boot', 'born', 'both', 'bowl', 'brag', 'bread', 'brick', 'brim',
    'brush', 'busy', 'cage', 'cake', 'calf', 'calm', 'camp', 'candy', 'card',
    'care', 'cart', 'case', 'cash', 'cast', 'cave', 'cent', 'chair', 'chat',
    'chef', 'chew', 'chin', 'chip', 'chop', 'city', 'clap', 'claw', 'clay',
    'clip', 'clock', 'cloud', 'club', 'clue', 'coal', 'coat', 'code', 'coin',
    'cold', 'colt', 'comb', 'cone', 'cook', 'cool', 'cope', 'copy', 'cord',
    'core', 'cork', 'corn', 'cost', 'cozy', 'crab', 'crew', 'crop', 'crow',
    'crown', 'cube', 'curb', 'cure', 'curl', 'dance', 'dare', 'dark', 'dart',
    'dawn', 'deal', 'dear', 'deck', 'deep', 'deer', 'dent', 'desk', 'dial',
    'dice', 'diet', 'dirt', 'dish', 'dive', 'dock', 'doll', 'dome', 'done',
    'door', 'dose', 'down', 'doze', 'drag', 'draw', 'dream', 'drip', 'drop',
    'drum', 'duck', 'dull', 'dusk', 'dust', 'duty', 'each', 'eagle', 'earn',
    'ease', 'east', 'easy', 'edge', 'exit', 'face', 'fact', 'fade', 'fail',
    'fair', 'fake', 'fall', 'fame', 'farm', 'fast', 'fawn', 'fear', 'feed',
    'feel', 'fell', 'felt', 'fence', 'fern', 'field', 'file', 'fill', 'film',
    'find', 'fine', 'fire', 'firm', 'fish', 'five', 'flag', 'flame', 'flap',
    'flat', 'flaw', 'flew', 'flip', 'flow', 'foam', 'fold', 'folk', 'fond',
    'food', 'fool', 'foot', 'fork', 'form', 'fort', 'four', 'free', 'frog',
    'from', 'frost', 'fuel', 'full', 'fund', 'fuzz', 'gain', 'game', 'gate',
    'gave', 'gaze', 'gear', 'gift', 'give', 'glad', 'glass', 'globe', 'glow',
    'glue', 'goal', 'goat', 'gold', 'gone', 'good', 'gown', 'grab', 'grape',
    'grass', 'gray', 'green', 'grew', 'grid', 'grin', 'grip', 'grow', 'gulf',
    'gust', 'half', 'hall', 'halt', 'hand', 'happy', 'hare', 'harm', 'harp',
    'heal', 'heap', 'hear', 'heart', 'heat', 'heel', 'help', 'herb', 'herd',
    'here', 'hide', 'high', 'hike', 'hill', 'hint', 'hive', 'hold', 'hole',
    'home', 'honey', 'hood', 'hoof', 'hook', 'hope', 'horn', 'horse', 'hose',
    'host', 'hour', 'house', 'howl', 'hunt', 'hurt', 'idea', 'inch', 'iron',
    'itch', 'item', 'jail', 'jazz', 'join', 'joke', 'jolt', 'jump', 'jury',
    'just', 'keen', 'keep', 'kelp', 'kept', 'kick', 'kind', 'king', 'kiss',
    'kite', 'knee', 'knew', 'knife', 'knit', 'knob', 'knot', 'lace', 'lack',
    'lake', 'lamb', 'lamp', 'land', 'lane', 'lark', 'last', 'late', 'lawn',
    'lazy', 'lead', 'leaf', 'lean', 'leap', 'left', 'lemon', 'lend', 'lens',
    'less', 'life', 'lift', 'light', 'like', 'lime', 'line', 'link', 'lion',
    'list', 'live', 'load', 'loaf', 'loan', 'lock', 'loft', 'lone', 'long',
    'look', 'loop', 'lord', 'lose', 'loss', 'lost', 'loud', 'love', 'luck',
    'lump', 'lung', 'made', 'mail', 'main', 'make', 'male', 'mane', 'many',
    'mare', 'mark', 'mask', 'mast', 'math', 'maze', 'meal', 'mean', 'meat',
    'melt', 'mend', 'menu', 'mesh', 'mess', 'mild', 'mile', 'milk', 'mind',
    'mine', 'mint', 'miss', 'mist', 'moat', 'mode', 'mole', 'money', 'mood',
    'moon', 'more', 'moss', 'most', 'moth', 'mouse', 'move', 'much', 'mule',
    'music', 'must', 'mute', 'myth', 'nail', 'name', 'navy', 'near', 'neat',
    'neck', 'need', 'nest', 'news', 'next', 'nice', 'night', 'nine', 'none',
    'noon', 'nose', 'note', 'noun', 'oath', 'obey', 'once', 'onion', 'only',
    'onto', 'open', 'oval', 'oven', 'over', 'pace', 'pack', 'page', 'paid',
    'pail', 'pain', 'pair', 'pale', 'palm', 'paper', 'park', 'part', 'pass',
    'past', 'path', 'pave', 'peach', 'peak', 'peel', 'peer', 'pile', 'pill',
    'pine', 'pink', 'pipe', 'plan', 'plant', 'plate', 'play', 'plot', 'plow',
    'plum', 'plus', 'poem', 'poet', 'pole', 'pond', 'pony', 'pool', 'poor',
    'porch', 'pork', 'port', 'pose', 'post', 'pour', 'pray', 'prey', 'prop',
    'pull', 'pump', 'pure', 'push', 'queen', 'quick', 'quiz', 'race', 'rack',
    'raft', 'rail', 'rain', 'rake', 'rank', 'rare', 'rash', 'rate', 'read',
    'real', 'reap', 'rear', 'reed', 'reef', 'reel', 'rent', 'rest', 'rice',
    'rich', 'ride', 'rind', 'ring', 'ripe', 'rise', 'risk', 'river', 'road',
    'roam', 'roar', 'robe', 'rock', 'role', 'roll', 'roof', 'room', 'root',
    'rope', 'rose', 'ruby', 'rude', 'ruin', 'rule', 'rush', 'rust', 'safe',
    'sage', 'sail', 'salad', 'sale', 'salt', 'same', 'sand', 'sang', 'sank',
    'save', 'scan', 'scar', 'seal', 'seam', 'seat', 'seed', 'seek', 'seem',
    'seen', 'self', 'sell', 'send', 'sent', 'shark', 'sharp', 'shed',
    'sheep', 'shelf', 'shin', 'ship', 'shoe', 'shop', 'shore', 'shot',
    'show', 'shut', 'sick', 'side', 'sift', 'sign', 'silk', 'sing', 'sink',
    'size', 'skid', 'skim', 'skin', 'skip', 'slab', 'slam', 'slap', 'sled',
    'sleep', 'slid', 'slim', 'slip', 'slot', 'slow', 'smile', 'snake',
    'snap', 'snip', 'snow', 'snug', 'soak', 'soap', 'soar', 'sock', 'sofa',
    'soft', 'soil', 'sold', 'sole', 'some', 'song', 'soon', 'sore', 'sort',
    'sound', 'soup', 'sour', 'space', 'spin', 'spoon', 'spot', 'spun',
    'stair', 'star', 'stem', 'step', 'stew', 'stir', 'stone', 'stop',
    'storm', 'story', 'straw', 'stub', 'such', 'sugar', 'suit', 'sung',
    'sure', 'surf', 'swam', 'swan', 'swap', 'swim', 'sword', 'table', 'tail',
    'tale', 'talk', 'tall', 'tame', 'tank', 'tape', 'task', 'team', 'tear',
    'tell', 'tend', 'tent', 'term', 'test', 'than', 'that', 'thaw', 'them',
    'then', 'they', 'thin', 'this', 'thus', 'tick', 'tide', 'tidy', 'tiger',
    'tile', 'till', 'tilt', 'time', 'tiny', 'tire', 'toad', 'toast', 'told',
    'toll', 'tomb', 'tone', 'took', 'tool', 'tooth', 'torch', 'torn', 'toss',
    'tour', 'town', 'trap', 'tray', 'tree', 'trim', 'trip', 'trot', 'tuck',
    'tune', 'turf', 'turn', 'twig', 'twin', 'type', 'unit', 'upon', 'urge',
    'vain', 'vane', 'vase', 'vast', 'veil', 'vein', 'verb', 'very', 'vest',
    'view', 'vine', 'visa', 'voice', 'vote', 'wade', 'wage', 'wait', 'wake',
    'walk', 'wall', 'wand', 'want', 'ward', 'ware', 'warm', 'warn', 'wart',
    'wash', 'wasp', 'water', 'wave', 'weak', 'wear', 'weed', 'week', 'weep',
    'well', 'went', 'were', 'west', 'whale', 'what', 'wheel', 'when', 'whip',
    'white', 'whom', 'wide', 'wife', 'wild', 'will', 'wilt', 'wind', 'wine',
    'wing', 'wink', 'wipe', 'wire', 'wise', 'wish', 'with', 'wolf', 'wood',
    'wool', 'word', 'wore', 'work', 'world', 'worm', 'worn', 'wove', 'wrap',
    'yard', 'yarn', 'yawn', 'year', 'yell', 'yolk', 'your', 'zeal', 'zest',
    'zinc', 'zone',
  ],

  // Tier 2 — everyday words whose misspellings look plausible.
  [
    'absorb', 'accent', 'access', 'advice', 'afford', 'agenda', 'almond',
    'amount', 'anchor', 'animal', 'ankle', 'answer', 'anthem', 'antler',
    'apron', 'archer', 'armor', 'aroma', 'arrive', 'artist', 'aspect',
    'assist', 'asthma', 'attend', 'attic', 'august', 'author', 'awake',
    'awful', 'bacon', 'badger', 'baker', 'bakery', 'bamboo', 'banana',
    'banner', 'barber', 'bargain', 'barley', 'barrel', 'basil', 'basin',
    'basket', 'batter', 'battle', 'beacon', 'beaver', 'beckon', 'bedding',
    'beetle', 'behave', 'bellow', 'belong', 'beside', 'better', 'beyond',
    'bishop', 'bitter', 'blazer', 'bleach', 'blister', 'boldly', 'bonnet',
    'border', 'borrow', 'bother', 'bottle', 'bounce', 'bracket', 'brains',
    'bramble', 'branch', 'brandy', 'breath', 'breeze', 'bridge', 'bridle',
    'bright', 'brittle', 'broken', 'bronze', 'brook', 'bubble', 'bucket',
    'buckle', 'budget', 'buffalo', 'builder', 'bundle', 'bunker', 'burden',
    'burrow', 'bushel', 'bustle', 'butter', 'button', 'cackle', 'cactus',
    'camel', 'camera', 'candid', 'candle', 'cannon', 'canoe', 'canvas',
    'canyon', 'carbon', 'career', 'carpet', 'carrot', 'cashew', 'castle',
    'casual', 'cavern', 'celery', 'cellar', 'cement', 'census', 'center',
    'cereal', 'chalk', 'chance', 'change', 'chapel', 'chapter', 'charge',
    'cheese', 'cherry', 'cherub', 'chicken', 'chilly', 'choice', 'chosen',
    'chrome', 'chuckle', 'circle', 'circus', 'civil', 'clamor', 'clever',
    'client', 'clinic', 'closet', 'clover', 'cluster', 'clutch', 'coast',
    'cobalt', 'coconut', 'coffee', 'collar', 'collect', 'column', 'comedy',
    'comfort', 'common', 'concert', 'consist', 'contest', 'convoy', 'copper',
    'corner', 'cortex', 'cotton', 'cousin', 'cradle', 'crater', 'crayon',
    'credit', 'cricket', 'crimson', 'crocus', 'crumble', 'crunch', 'culture',
    'custom', 'cymbal', 'damage', 'dampen', 'danger', 'dapper', 'dazzle',
    'debate', 'decade', 'decent', 'degree', 'delta', 'deputy', 'desert',
    'design', 'desire', 'dessert', 'detail', 'device', 'devote', 'diagram',
    'dilute', 'dimple', 'dinner', 'divide', 'docket', 'doctor', 'donkey',
    'doodle', 'double', 'dozen', 'dragon', 'dresser', 'drift', 'driver',
    'duffel', 'dugout', 'duplex', 'during', 'eager', 'earnest', 'easel',
    'effort', 'either', 'eleven', 'embark', 'ember', 'emblem', 'emerge',
    'empire', 'enable', 'engine', 'enrich', 'ensure', 'entire', 'equal',
    'escape', 'estate', 'ethics', 'event', 'evolve', 'exact', 'exile',
    'expand', 'expert', 'export', 'extend', 'fabric', 'falcon', 'fallow',
    'family', 'famous', 'fasten', 'father', 'fathom', 'feast', 'feather',
    'fellow', 'fender', 'fiddle', 'fierce', 'figure', 'filter', 'finger',
    'finish', 'flannel', 'flavor', 'fleece', 'flight', 'floral', 'flower',
    'flurry', 'flute', 'follow', 'fondue', 'forest', 'forget', 'formal',
    'former', 'fossil', 'foster', 'fourth', 'foyer', 'friend', 'frugal',
    'fumble', 'funnel', 'future', 'gadget', 'galaxy', 'gallon', 'gallop',
    'garage', 'garden', 'garlic', 'gather', 'gentle', 'gerbil', 'geyser',
    'giant', 'giggle', 'ginger', 'giraffe', 'glance', 'glitter', 'goblet',
    'goblin', 'golden', 'gopher', 'gospel', 'gossip', 'gourd', 'grace',
    'grader', 'grain', 'grand', 'grant', 'grasp', 'gravel', 'gravy',
    'grocer', 'ground', 'growth', 'guitar', 'gutter', 'habit', 'hammer',
    'hamper', 'handle', 'happen', 'harbor', 'hazard', 'header', 'health',
    'hearth', 'heaven', 'hedge', 'helmet', 'herald', 'hermit', 'heroic',
    'hiccup', 'hidden', 'hollow', 'honest', 'hornet', 'hotel', 'hubris',
    'humble', 'hunger', 'hurdle', 'hybrid', 'hyphen', 'icicle', 'ignite',
    'immune', 'impact', 'import', 'income', 'indeed', 'indigo', 'infant',
    'inform', 'insect', 'inside', 'invite', 'island', 'jacket', 'jaguar',
    'jargon', 'jigsaw', 'jingle', 'jockey', 'jungle', 'kennel', 'kernel',
    'kettle', 'kindle', 'kitten', 'knight', 'ladder', 'lagoon', 'lantern',
    'lapel', 'laptop', 'lately', 'lawyer', 'leader', 'legend', 'length',
    'lentil', 'lesson', 'letter', 'lettuce', 'level', 'lichen', 'likely',
    'lilac', 'limber', 'linger', 'litter', 'little', 'lively', 'lizard',
    'lobby', 'lobster', 'locket', 'locust', 'lodge', 'lonely', 'loyal',
    'lumber', 'luster', 'luxury', 'magnet', 'magpie', 'mallet', 'mammal',
    'mango', 'manner', 'mantis', 'mantle', 'marble', 'margin', 'marina',
    'market', 'marrow', 'marvel', 'mascot', 'matter', 'meadow', 'medal',
    'medium', 'mellow', 'melody', 'member', 'memory', 'mentor', 'merge',
    'merit', 'method', 'middle', 'mimic', 'mingle', 'minnow', 'minute',
    'mirror', 'mister', 'mitten', 'mixture', 'modern', 'modest', 'moment',
    'monkey', 'month', 'morsel', 'mosaic', 'mother', 'motion', 'motive',
    'muffin', 'murmur', 'museum', 'mustard', 'mutual', 'myself', 'napkin',
    'narrow', 'nation', 'nature', 'nectar', 'needle', 'nephew', 'nestle',
    'nickel', 'nimble', 'nobody', 'normal', 'notice', 'novel', 'nugget',
    'number', 'nurse', 'nutmeg', 'object', 'oblong', 'obtain', 'occupy',
    'office', 'omelet', 'openly', 'orange', 'orchid', 'ordeal', 'orient',
    'origin', 'osprey', 'ostrich', 'outfit', 'outlet', 'oxygen', 'oyster',
    'paddle', 'palace', 'pallet', 'pantry', 'papaya', 'parade', 'parcel',
    'pardon', 'parent', 'parlor', 'parrot', 'parsley', 'patrol', 'pauper',
    'pebble', 'pedal', 'pellet', 'pencil', 'people', 'pepper', 'perch',
    'period', 'permit', 'person', 'pewter', 'phrase', 'picnic', 'pigeon',
    'pillar', 'pillow', 'pilot', 'pincer', 'pirate', 'pistil',
    'pitch', 'planet', 'plaque', 'plasma', 'please', 'pledge', 'plenty',
    'pliers', 'plural', 'pocket', 'poetry', 'polish', 'pollen', 'ponder',
    'poplar', 'poppy', 'porous', 'portal', 'poster', 'potato', 'pottery',
    'powder', 'praise', 'prance', 'prefer', 'pretty', 'pretzel', 'prince',
    'prism', 'prompt', 'proper', 'proton', 'public', 'puddle', 'pulley',
    'pulpit', 'pumpkin', 'punish', 'pupil', 'puppet', 'purple', 'pursue',
    'puzzle', 'python', 'quartz', 'quench', 'quiver', 'rabbit', 'raccoon',
    'radish', 'rafter', 'ragged', 'raisin', 'rally', 'ramble', 'rancher',
    'random', 'rascal', 'rather', 'ratio', 'ravine', 'reason', 'recent',
    'recipe', 'reckon', 'record', 'reduce', 'reflex', 'refuge', 'region',
    'relish', 'remain', 'remedy', 'remind', 'remote', 'render', 'rental',
    'repair', 'repeat', 'report', 'rescue', 'resin', 'result', 'retain',
    'return', 'reveal', 'reward', 'rhubarb', 'ribbon', 'riddle', 'ripple',
    'ritual', 'robust', 'rocket', 'rodent', 'roster', 'rotate', 'rubber',
    'rumble', 'runner', 'runway', 'rustic', 'rustle', 'sacred', 'saddle',
    'safari', 'salmon', 'salute', 'sample', 'sandal', 'sapling', 'scarf',
    'scenic', 'school', 'scoop', 'scorch', 'scrap', 'screen', 'script',
    'scroll', 'sculpt', 'season', 'second', 'secret', 'sector', 'seldom',
    'select', 'senior', 'sensor', 'sermon', 'settle', 'severe', 'shadow',
    'shampoo', 'shatter', 'shelter', 'sheriff', 'shimmer', 'shovel',
    'shower', 'shrimp', 'shrine', 'signal', 'silent', 'silver', 'simple',
    'singer', 'sister', 'sizzle', 'sketch', 'slalom', 'sleeve', 'slogan',
    'smooth', 'snooze', 'soccer', 'social', 'socket', 'sodium', 'solemn',
    'sonnet', 'sorrow', 'speech', 'sphere', 'spider', 'spiral', 'spirit',
    'splash', 'sponge', 'spouse', 'spring', 'sprout', 'squash', 'squire',
    'stable', 'stadium', 'stanza', 'staple', 'statue', 'steady', 'stereo',
    'sticky', 'stitch', 'stormy', 'street', 'stride', 'stripe', 'stroll',
    'strong', 'student', 'studio', 'sturdy', 'subtle', 'suburb', 'sudden',
    'summer', 'summit', 'sunny', 'sunset', 'supper', 'survey', 'swivel',
    'symbol', 'system', 'tackle', 'tactic', 'talent', 'tangle', 'tassel',
    'tavern', 'temper', 'temple', 'tender', 'tennis', 'thicket', 'thimble',
    'thirty', 'thistle', 'thread', 'thrive', 'throne', 'ticket', 'timber',
    'tissue', 'toffee', 'tomato', 'tongue', 'trader', 'traffic', 'tragic',
    'trance', 'travel', 'treaty', 'tremor', 'trench', 'tribute', 'tricky',
    'trolley', 'trophy', 'trumpet', 'trust', 'tumble', 'tundra', 'tunnel',
    'turkey', 'turnip', 'turtle', 'twelve', 'twenty', 'twinkle', 'typical',
    'umpire', 'unfold', 'unique', 'unless', 'untidy', 'update', 'upward',
    'urgent', 'useful', 'usual', 'utmost', 'valley', 'vanish', 'vapor',
    'vault', 'velvet', 'vendor', 'verify', 'vessel', 'viable', 'violet',
    'violin', 'visit', 'visual', 'vivid', 'volume', 'voyage', 'waffle',
    'wagon', 'walnut', 'wander', 'weasel', 'weekly', 'whisper', 'wicker',
    'widget', 'willow', 'window', 'winner', 'winter', 'wisdom', 'wither',
    'wizard', 'wombat', 'wonder', 'wooden', 'worthy', 'wrench', 'yellow',
    'yonder', 'zealous', 'zenith', 'zipper', 'zither',
  ],

  // Tier 3 — longer words, real spelling traps.
  [
    'abdomen', 'abrasive', 'absolute', 'abundant', 'academic', 'accident',
    'account', 'accuracy', 'accurate', 'achieve', 'acidity', 'acoustic',
    'acrobat', 'activist', 'actually', 'address', 'adequate', 'adhesive',
    'adjacent', 'admirable', 'adorable', 'advance', 'advocate', 'affection',
    'ailment', 'airfield', 'airliner', 'airport', 'alarming', 'alligator',
    'alphabet', 'already', 'although', 'altitude', 'ambition', 'amplify',
    'amusing', 'analysis', 'anatomy', 'ancestor', 'anchovy', 'ancient',
    'angular', 'animated', 'announce', 'annoying', 'antelope', 'antibody',
    'antique', 'anxious', 'anywhere', 'apology', 'apparent', 'appetite',
    'applause', 'approach', 'approval', 'apricot', 'aquarium', 'aqueduct',
    'aquifer', 'armchair', 'aromatic', 'arrival', 'arrogant', 'article',
    'artisan', 'artistic', 'assembly', 'asteroid', 'atheist', 'athlete',
    'athletic', 'attempt', 'attention', 'attitude', 'attorney', 'audible',
    'audience', 'audition', 'auditor', 'autopilot', 'autumn', 'avenue',
    'average', 'avocado', 'awkward', 'bachelor', 'backbone', 'backpack',
    'backward', 'baggage', 'balance', 'balcony', 'balloon', 'bandage',
    'banister', 'barbecue', 'barnacle', 'barrister', 'baseball', 'basement',
    'bassoon', 'bathroom', 'bearable', 'because', 'bedroom', 'beetroot',
    'begonia', 'believe', 'benefit', 'betrayal', 'between', 'beverage',
    'bewilder', 'biannual', 'bicycle', 'billiard', 'biology', 'birthday',
    'biscuit', 'blanket', 'blending', 'blessing', 'blissful', 'blizzard',
    'blossom', 'bluebell', 'boarding', 'bookcase', 'botanist', 'boundary',
    'bracelet', 'bracken', 'breathe', 'broccoli', 'brochure', 'brought',
    'building', 'bungalow', 'buoyancy', 'buoyant', 'burglar', 'business',
    'bustling', 'buzzard', 'cabbage', 'cabinet', 'calcium', 'calculate',
    'calendar', 'campaign', 'canister', 'capable', 'capacity', 'capsicum',
    'captain', 'capture', 'capybara', 'caramel', 'caravan', 'cardamom',
    'cardiac', 'cardinal', 'careless', 'caribou', 'carnival', 'carousel',
    'carriage', 'cascade', 'casserole', 'catalyst', 'category', 'cathedral',
    'cattle', 'causeway', 'caution', 'cautious', 'cedarwood', 'ceiling',
    'cemetery', 'centipede', 'century', 'ceramic', 'certain', 'chamber',
    'champion', 'channel', 'chaplain', 'charcoal', 'charity', 'charming',
    'checkers', 'cheerful', 'cheetah', 'chemical', 'chemist', 'chestnut',
    'chickpea', 'chimney', 'chipmunk', 'chivalry', 'chorus', 'cilantro',
    'cinnamon', 'circular', 'cistern', 'citizen', 'civilian', 'clarinet',
    'classical', 'clematis', 'climate', 'clockwise', 'coastal', 'cockatoo',
    'colander', 'collapse', 'college', 'colonist', 'colorful', 'colossal',
    'comedian', 'comical', 'commence', 'communal', 'commuter', 'compact',
    'company', 'compass', 'composer', 'compound', 'computer', 'concede',
    'concerto', 'conclude', 'concrete', 'condemn', 'confetti', 'conifer',
    'conquer', 'constant', 'consumer', 'contrast', 'converse', 'conveyor',
    'corduroy', 'corridor', 'costume', 'cottage', 'country', 'courage',
    'courier', 'courtesy', 'coverage', 'creation', 'creative', 'creature',
    'credible', 'creeper', 'crescent', 'critical', 'crockery', 'crossing',
    'crucial', 'crystal', 'cucumber', 'cultural', 'cupboard', 'curator',
    'curious', 'currant', 'currents', 'curtain', 'curvature', 'cushion',
    'custard', 'cycling', 'cyclone', 'cylinder', 'cypress', 'daffodil',
    'daughter', 'daybreak', 'daydream', 'daylight', 'dazzling', 'deadline',
    'decanter', 'deceive', 'decision', 'decisive', 'decorate', 'deferred',
    'definite', 'delegate', 'delicate', 'delicious', 'delight', 'delivery',
    'density', 'dentist', 'descent', 'describe', 'designer', 'detailed',
    'devotion', 'diagonal', 'dialect', 'dialogue', 'diameter', 'diamond',
    'dictator', 'dilemma', 'diligent', 'dinosaur', 'diplomat', 'director',
    'disciple', 'discover', 'disguise', 'dissect', 'dissolve', 'distance',
    'distant', 'distinct', 'diverse', 'dividend', 'dockyard', 'doctrine',
    'doldrums', 'dolphin', 'domestic', 'dominant', 'donation', 'doorknob',
    'doormat', 'doorstep', 'dormouse', 'doubtful', 'downhill', 'dramatic',
    'drawer', 'dreadful', 'dressing', 'driftwood', 'driveway', 'drizzle',
    'drought', 'drumbeat', 'duckling', 'dumbbell', 'dumpling', 'dumpster',
    'durable', 'duration', 'dwelling', 'dynamic', 'dynamite', 'eardrum',
    'earnings', 'earphone', 'earthly', 'eastern', 'eastward', 'echoes',
    'eclipse', 'ecology', 'economy', 'educator', 'eggplant',
    'eighteen', 'elaborate', 'election', 'electron', 'elegant', 'elephant',
    'elevator', 'eligible', 'eloquent', 'embellish', 'emperor', 'emphasis',
    'emphatic', 'employee', 'employer', 'endless', 'engineer', 'enormous',
    'entrance', 'envelope', 'epilogue', 'equation', 'equator', 'equipped',
    'erosion', 'escalate', 'escarole', 'especial', 'estimate', 'estuary',
    'etching', 'eternal', 'eternity', 'ethical', 'evening', 'eventual',
    'evidence', 'evident', 'examiner', 'example', 'exchange', 'exciting',
    'exercise', 'expanse', 'explorer', 'exposure', 'exquisite', 'exterior',
    'eyebrow', 'eyelash', 'eyesight', 'fabulous', 'fanlight', 'fantasy',
    'farewell', 'farmhand', 'fashion', 'fearless', 'feasible', 'feathery',
    'feature', 'feminine', 'fernery', 'festival', 'fiction', 'fiddler',
    'fifteen', 'fifteenth', 'filament', 'firefly', 'firewood', 'fissure',
    'fixture', 'flamingo', 'flapjack', 'flautist', 'flawless', 'flexible',
    'florist', 'flounder', 'foliage', 'folklore', 'folktale', 'football',
    'forearm', 'forecast', 'forehead', 'foreign', 'foreman', 'forfeit',
    'fortress', 'fortune', 'fountain', 'foxglove', 'fracture', 'fragile',
    'fragrant', 'frantic', 'freckle', 'freedom', 'freeway', 'freezing',
    'frequent', 'friction', 'frontier', 'fruitful', 'fuchsia', 'fulfill',
    'function', 'furious', 'furnace', 'furthest', 'galleon', 'gallery',
    'gardener', 'gargoyle', 'garment', 'gateway', 'gazelle', 'gazette',
    'gemstone', 'general', 'generous', 'genuine', 'geometry', 'geranium',
    'glacier', 'glorious', 'glossary', 'goldfish', 'gondola', 'goshawk',
    'governor', 'graceful', 'gracious', 'gradient', 'gradual', 'graduate',
    'grammar', 'granary', 'grandeur', 'granite', 'granola', 'grateful',
    'gravity', 'greeting', 'grimace', 'guardian', 'guidance', 'gymnast',
    'habitat', 'hallway', 'hammock', 'hamster', 'handball', 'handbook',
    'handcart', 'handrail', 'handsome', 'hardware', 'harmless', 'harmonic',
    'harmony', 'harvest', 'hawthorn', 'hazelnut', 'headache', 'headlamp',
    'headline', 'healthy', 'hedgehog', 'heirloom', 'herdsman', 'heritage',
    'herring', 'hesitant', 'hesitate', 'hibernate', 'hibiscus', 'highway',
    'hilarious', 'historic', 'history', 'holiday', 'homemade', 'honeydew',
    'hopeless', 'horizon', 'hormone', 'hornbill', 'hospital', 'humidity',
    'hundred', 'hurried', 'hyacinth', 'hydrogen', 'hygiene', 'iceberg',
    'icebound', 'identity', 'igneous', 'illusion', 'imaginary', 'imagine',
    'immense', 'immunity', 'imperial', 'impulse', 'incident', 'incubate',
    'indicate', 'industry', 'infamous', 'infinite', 'informal', 'innocent',
    'inquiry', 'inspire', 'instance', 'instant', 'intense', 'interior',
    'interval', 'intrepid', 'inventor', 'investor', 'ironwork', 'irrigate',
    'isolate', 'isotope', 'janitor', 'january', 'jasmine', 'javelin',
    'jawbone', 'jealous', 'jewelry', 'journey', 'jubilant', 'judgment',
    'jugglery', 'junction', 'juniper', 'kangaroo', 'keepsake', 'kestrel',
    'keyboard', 'kindness', 'kingdom', 'kitchen', 'kneecap', 'knuckle',
    'kohlrabi', 'laborer', 'laborious', 'laburnum', 'ladybird', 'laminate',
    'landlord', 'landmark', 'larkspur', 'latchkey', 'latitude', 'laughter',
    'laundry', 'lavender', 'lawmaker', 'leather', 'lecture', 'lecturer',
    'leisure', 'lemming', 'lemonade', 'leopard', 'liaison', 'liberal',
    'liberty', 'library', 'libretto', 'license', 'lifeboat', 'lifetime',
    'ligament', 'limerick', 'linguist', 'linoleum', 'liquefy', 'listener',
    'literacy', 'literary', 'lockbox', 'logical', 'lonesome', 'luggage',
    'lullaby', 'luminous', 'luncheon', 'lyricist', 'macaroni', 'machine',
    'magnetic', 'magnolia', 'mahogany', 'mailbox', 'majestic', 'mallard',
    'manager', 'manatee', 'mandarin', 'mandolin', 'mandrill', 'maneuver',
    'mangrove', 'mansion', 'marathon', 'marigold', 'marinade', 'mariner',
    'maritime', 'marjoram', 'marmoset', 'marriage', 'marshal', 'masonry',
    'massive', 'mattress', 'maximum', 'mayoral', 'meanwhile', 'measure',
    'mechanic', 'mediator', 'medical', 'medicine', 'medieval', 'mediocre',
    'meerkat', 'melodic', 'memento', 'merchant', 'merciful', 'meridian',
    'meringue', 'message', 'metallic', 'methane', 'microbe', 'midnight',
    'midweek', 'midwife', 'migraine', 'migrate', 'milestone', 'militia',
    'mineral', 'miniature', 'minister', 'minstrel', 'miracle', 'mischief',
    'misspell', 'moderate', 'moisture', 'molasses', 'molecule', 'momentum',
    'mongoose', 'monsoon', 'monster', 'montage', 'monument', 'moorhen',
    'morning', 'mortgage', 'mosquito', 'motorway', 'mournful', 'movement',
    'multiple', 'muscular', 'mushroom', 'musical', 'musician', 'mystery',
    'mystical', 'narrator', 'national', 'natural', 'naughty', 'nautical',
    'navigate', 'necklace', 'negative', 'neighbor', 'neither', 'nervous',
    'netball', 'neutral', 'neutron', 'newcomer', 'nineteen', 'nitrogen',
    'nocturne', 'northern', 'nostril', 'notation', 'notebook', 'novelist',
    'novella', 'nowadays', 'nuisance', 'numerous', 'nursery', 'nuthatch',
    'nutrient', 'oatmeal', 'obscure', 'observe', 'observer', 'obvious',
    'occupant', 'oceanic', 'october', 'octopus', 'officer', 'official',
    'offshore', 'ointment', 'oleander', 'omelette', 'omission', 'omitted',
    'operator', 'operetta', 'opinion', 'opossum', 'opponent', 'opposite',
    'optician', 'optimism', 'orchard', 'ordinary', 'oregano', 'organic',
    'organism', 'origami', 'original', 'ornament', 'orthodox', 'outburst',
    'outcome', 'outcrop', 'outsider', 'overcast', 'overcoat', 'overcome',
    'overlook', 'overpass', 'overseer', 'overture', 'padlock', 'painting',
    'pamphlet', 'pancake', 'panther', 'paprika', 'paradise', 'paragraph',
    'parakeet', 'paralyze', 'parasol', 'parkway', 'parmesan', 'parsnip',
    'particle', 'passenger', 'passport', 'pastime', 'pastoral', 'pathway',
    'patience', 'patient', 'patriot', 'pattern', 'pavement', 'pavilion',
    'peaceful', 'peacock', 'pedestal', 'pelican', 'pendulum', 'penguin',
    'peninsula', 'perceive', 'perfect', 'perfume', 'perimeter', 'periodic',
    'personal', 'petition', 'petunia', 'pheasant', 'physical', 'pianist',
    'picture', 'pilgrim', 'pinnacle', 'pioneer', 'pipeline', 'plankton',
    'plateau', 'platform', 'platinum', 'platypus', 'playbill', 'pleasant',
    'plentiful', 'plumbing', 'politely', 'popcorn', 'populace', 'popular',
    'porpoise', 'porridge', 'portable', 'porthole', 'portrait', 'portray',
    'position', 'positive', 'possible', 'postbox', 'postcard', 'posture',
    'powerful', 'practical', 'practice', 'preacher', 'precede', 'precinct',
    'precise', 'predator', 'predict', 'presence', 'preserve', 'pressure',
    'previous', 'primary', 'primrose', 'princess', 'printer', 'priority',
    'prisoner', 'probable', 'probably', 'problem', 'proceed', 'producer',
    'profound', 'promise', 'promoter', 'prosper', 'protect', 'protein',
    'proverb', 'provided', 'provider', 'province', 'prudent', 'punctual',
    'puppetry', 'purchase', 'pyramid', 'quarter', 'quarterly', 'quartet',
    'quatrain', 'quilting', 'quotient', 'racquet', 'radiance', 'radiant',
    'radiator', 'railings', 'railway', 'rainbow', 'rainfall', 'rational',
    'ravioli', 'reaction', 'reassure', 'rebuild', 'receipt', 'receive',
    'recital', 'reckless', 'recover', 'recovery', 'recruit', 'rectangle',
    'referee', 'referred', 'reformer', 'regional', 'register', 'regular',
    'reindeer', 'relative', 'relevant', 'reliable', 'relieve', 'remember',
    'renegade', 'renowned', 'reptile', 'require', 'research', 'reserve',
    'resident', 'resource', 'respect', 'response', 'restless', 'retailer',
    'reunion', 'revision', 'rhapsody', 'rhetoric', 'rhyming', 'rigorous',
    'riverbed', 'roadside', 'romantic', 'rooftop', 'rosemary', 'rotation',
    'roundup', 'rucksack', 'rutabaga', 'saffron', 'sailboat', 'salesman',
    'sanctuary', 'sapphire', 'satchel', 'saturday', 'sausage', 'savanna',
    'sawmill', 'scaffold', 'scallion', 'scarcity', 'scenario', 'scenery',
    'schedule', 'scholar', 'science', 'scooter', 'scoring', 'scorpion',
    'scramble', 'sculptor', 'seafront', 'seagull', 'seahorse', 'seasonal',
    'seaweed', 'sediment', 'seismic', 'semester', 'semitone', 'semolina',
    'senator', 'sensible', 'sentence', 'sequence', 'sequoia', 'serenade',
    'sergeant', 'serious', 'settler', 'seventeen', 'shepherd', 'shipyard',
    'shoulder', 'sidecar', 'sidewalk', 'signature', 'signpost', 'silently',
    'silicon', 'similar', 'skeleton', 'skillful', 'skirmish', 'skylark',
    'skylight', 'slippery', 'smoothie', 'smuggler', 'snooker', 'snowdrop',
    'sociable', 'solitary', 'solitude', 'solstice', 'solution', 'songbird',
    'southern', 'spacious', 'spaniel', 'sparrow', 'special', 'specific',
    'specimen', 'spectrum', 'spelling', 'spinach', 'splendid', 'splinter',
    'sponsor', 'sporadic', 'sprinkle', 'squadron', 'squirrel', 'standard',
    'starfish', 'starling', 'steeple', 'sterling', 'steward', 'stingray',
    'stomach', 'stovetop', 'straddle', 'strange', 'stranger', 'strategy',
    'striking', 'structure', 'struggle', 'stubborn', 'succeed', 'suitable',
    'suitcase', 'sundial', 'sundown', 'sunlight', 'sunrise', 'sunshine',
    'superior', 'suppress', 'surgeon', 'surgery', 'surround', 'surveyor',
    'swallow', 'swifter', 'sycamore', 'syllable', 'symbolic', 'symmetry',
    'sympathy', 'symptom', 'synonym', 'tadpole', 'tamarind', 'tangible',
    'tapestry', 'tapioca', 'tarragon', 'teacher', 'teammate', 'teaspoon',
    'telegram', 'telescope', 'tendency', 'terminal', 'terrain', 'terrapin',
    'terrible', 'terrific', 'textbook', 'texture', 'theater', 'therapy',
    'thermal', 'thirteen', 'thorough', 'thought', 'thousand', 'threshold',
    'through', 'thunder', 'timeless', 'timeline', 'together', 'tolerant',
    'tonight', 'toolbox', 'topsoil', 'tornado', 'tortilla', 'tortoise',
    'tourism', 'tragedy', 'trainer', 'tramway', 'tranquil', 'transfer',
    'transit', 'trapdoor', 'treasure', 'treatment', 'trellis', 'tremble',
    'triangle', 'tribunal', 'triumph', 'trombone', 'tropical', 'trouble',
    'trustee', 'tsunami', 'turbine', 'turmeric', 'turnpike', 'turquoise',
    'tutorial', 'twelfth', 'tyranny', 'ukulele', 'ultimate', 'underdog',
    'undergo', 'uniform', 'universe', 'unusual', 'upstream', 'utensil',
    'vacation', 'vaccine', 'validate', 'valuable', 'vanguard', 'vanilla',
    'variable', 'variety', 'various', 'vehicle', 'velocity', 'veranda',
    'verbena', 'vertebra', 'vertical', 'veteran', 'viaduct', 'vibrant',
    'vicious', 'victory', 'vigilant', 'vignette', 'vigorous', 'village',
    'villager', 'villain', 'vinegar', 'vintage', 'violent', 'virtual',
    'visible', 'visitor', 'vitamin', 'vocation', 'volcanic', 'volcano',
    'voltage', 'voyager', 'vulture', 'waistcoat', 'waitress', 'wanderer',
    'warbler', 'wardrobe', 'warrant', 'warranty', 'warrior', 'watchful',
    'waterfall', 'waterway', 'wayfarer', 'wealthy', 'weather', 'weekday',
    'weekend', 'weight', 'westward', 'wetland', 'whatever', 'wherever',
    'whether', 'whirlwind', 'whistle', 'wholesome', 'wildfire', 'wildlife',
    'windmill', 'windpipe', 'wingspan', 'wireless', 'wirework', 'wisteria',
    'withhold', 'wondrous', 'woodland', 'woodwind', 'woodwork', 'wordplay',
    'workbook', 'workshop', 'wrinkle', 'writing', 'yearbook', 'yearling',
    'yearning', 'yielding', 'youthful',
  ],

  // Tier 4 — the classic hard spellings.
  [
    'abandonment', 'abbreviate', 'abbreviation', 'abnormality', 'abolition',
    'absolutely', 'absorbent', 'absorption', 'abstraction', 'acceleration',
    'acceptance', 'accessible', 'accessories', 'accidentally', 'accommodate',
    'accomplish', 'accordingly', 'accordion', 'accountable', 'accountant',
    'accumulate', 'accumulation', 'accusations', 'achievement',
    'acknowledge', 'acquaintance', 'acquiesce', 'acquisition', 'acrobatics',
    'activation', 'adaptability', 'adaptable', 'adaptation', 'additionally',
    'adjustment', 'admiration', 'admissible', 'admission', 'adolescence',
    'adolescent', 'advancement', 'advantageous', 'adventure', 'adventurous',
    'adversary', 'aeronautics', 'affectionate', 'affiliation', 'affirmation',
    'affordable', 'aftermath', 'afternoon', 'aggravate', 'aggregation',
    'aggressive', 'agreeable', 'agreement', 'agriculture', 'albatross',
    'alignments', 'allegiance', 'alleviation', 'alliteration', 'allocation',
    'allowance', 'alphabetical', 'alteration', 'alternating', 'alternative',
    'altogether', 'amazement', 'ambassador', 'ambidextrous', 'ambiguous',
    'ambitious', 'ambulance', 'amendment', 'amphibian', 'analytically',
    'anniversary', 'announcement', 'announcer', 'annoyance', 'anonymous',
    'antarctic', 'anthology', 'anthropology', 'antibiotic', 'anticipate',
    'anticipation', 'antiquities', 'apologetic', 'apostrophe', 'apothecary',
    'appalling', 'apparatus', 'apparently', 'appealing', 'appearance',
    'appeasement', 'appetizer', 'appliance', 'applicable', 'application',
    'appointment', 'appreciable', 'appreciate', 'appreciation',
    'apprehension', 'apprentice', 'approachable', 'appropriate',
    'approximate', 'aquamarine', 'aquarelle', 'arbitrary', 'archipelago',
    'architect', 'architecture', 'archivist', 'arithmetic', 'arithmetical',
    'armadillo', 'arrangement', 'artichoke', 'articulation', 'artificial',
    'asparagus', 'assertion', 'assessment', 'assignment', 'assimilation',
    'assistance', 'assistant', 'associate', 'associations', 'assortment',
    'assumption', 'assurance', 'astonish', 'astronaut', 'astronautics',
    'astronomer', 'astronomical', 'astronomy', 'atmosphere', 'atmospheric',
    'attachment', 'attainment', 'attendance', 'attentive', 'attraction',
    'attractive', 'aubergine', 'audacious', 'audiovisual', 'auditorium',
    'authentic', 'authenticity', 'authority', 'autographed', 'automatic',
    'automation', 'autonomously', 'auxiliary', 'availability', 'available',
    'avalanche', 'avoidance', 'awakening', 'awareness', 'backgrounds',
    'bacteria', 'bacteriology', 'badminton', 'ballerina', 'balustrade',
    'bandleader', 'bandstand', 'bankruptcy', 'bannister', 'barometer',
    'basically', 'basketball', 'beautiful', 'beforehand', 'beginning',
    'believable', 'benefactor', 'beneficial', 'beneficiary', 'bewildered',
    'bewilderment', 'bibliography', 'binoculars', 'biochemical',
    'biodiversity', 'biographer', 'biographical', 'biography', 'biological',
    'birdhouse', 'bittersweet', 'blackberry', 'blackbird', 'blacksmiths',
    'bloodhound', 'bloodstream', 'blueberry', 'blueprint', 'bodyguard',
    'boisterous', 'bookbinding', 'bookkeeper', 'bookkeeping', 'bookshelf',
    'bootstrapped', 'botanically', 'boulevard', 'boundless', 'breadcrumb',
    'breadwinner', 'breakfast', 'breakthrough', 'breathlessly',
    'breathtaking', 'brickwork', 'briefcase', 'brightening', 'brilliant',
    'broadcaster', 'broadcloth', 'broadening', 'brotherhood', 'bulldozer',
    'bullfinch', 'bumblebee', 'bureaucracy', 'buttercup', 'butterfly',
    'buttermilk', 'buttonholes', 'bystander', 'calculation', 'calculator',
    'calibration', 'calligraphy', 'camaraderie', 'camouflage', 'campgrounds',
    'cancellation', 'candidacy', 'candidate', 'candlelight', 'candlestick',
    'cantaloupe', 'capability', 'capillary', 'captivating', 'carbohydrate',
    'carbonate', 'cardboard', 'carelessness', 'caretaker', 'caricature',
    'carnation', 'carpenter', 'cartilage', 'cartographer', 'cartography',
    'cartoonist', 'cartridge', 'catastrophe', 'caterpillar', 'cauliflower',
    'celebrate', 'celebration', 'cellulose', 'centenary', 'centennial',
    'centigrade', 'centrepiece', 'ceremonial', 'ceremony', 'certainty',
    'certificate', 'challenge', 'chameleon', 'championship', 'chancellor',
    'chandelier', 'changeable', 'character', 'charismatic', 'charitable',
    'chauffeur', 'checkerboard', 'checkpoint', 'cheerfulness', 'chemistry',
    'chessboards', 'chimpanzee', 'chinchilla', 'chivalrous', 'chloroform',
    'chlorophyll', 'chocolate', 'choreography', 'chorister', 'chromosome',
    'chronicle', 'chronology', 'circulation', 'circumstance', 'civilization',
    'civilized', 'clapboard', 'clarinettist', 'cleanliness', 'cleansing',
    'clementine', 'clinician', 'clipboard', 'clockmakers', 'clockwork',
    'clothesline', 'coastline', 'cobblestone', 'coincidence', 'collaborate',
    'collaborator', 'collarbone', 'colleague', 'collectible', 'collection',
    'collision', 'colloquial', 'colonnades', 'colourless', 'columnist',
    'combination', 'combustion', 'comfortable', 'commander', 'commemorate',
    'commencement', 'commendable', 'commentary', 'commentator', 'commercial',
    'commission', 'commitment', 'committee', 'commonplace', 'communicate',
    'community', 'companion', 'comparable', 'comparative', 'comparison',
    'compartment', 'compassion', 'compatible', 'compensation', 'competent',
    'competition', 'competitive', 'compilation', 'complacency',
    'complaining', 'completely', 'completeness', 'completion', 'complexion',
    'complexity', 'compliance', 'complicated', 'compliment', 'composition',
    'compression', 'compromise', 'computation', 'concentrate', 'conception',
    'conceptually', 'concessions', 'conclusion', 'concourse', 'condensation',
    'condition', 'conductivity', 'conductor', 'confectioner', 'confederacy',
    'conference', 'confidence', 'confident', 'confidential', 'confinement',
    'confirmation', 'conflicting', 'confusion', 'congratulate',
    'congregation', 'conjunction', 'connection', 'conscience', 'conscious',
    'consecutive', 'consensus', 'consequence', 'conservation',
    'conservatory', 'considerable', 'consistency', 'consistent',
    'consolation', 'consolidate', 'consonant', 'conspicuous', 'constitution',
    'constrained', 'construction', 'constructive', 'consultant',
    'consultation', 'consumption', 'contagious', 'container', 'containment',
    'contaminate', 'contemplate', 'contemporary', 'contentment', 'continent',
    'continental', 'contingency', 'continuation', 'continuous', 'contractor',
    'contradict', 'contribution', 'contributor', 'controversy',
    'convenience', 'conventional', 'conversation', 'conversion',
    'convertible', 'conviction', 'convincingly', 'cooperate', 'cooperation',
    'cooperative', 'coordinated', 'coordination', 'copyrighted', 'coriander',
    'cormorant', 'cornbread', 'cornerstone', 'cornflour', 'corollary',
    'corporation', 'correction', 'correlation', 'correspond', 'corrosion',
    'corruption', 'cottontail', 'counselor', 'counterpart', 'countertop',
    'countryside', 'courageous', 'courgette', 'coursework', 'courteous',
    'courtyard', 'craftsman', 'cranberry', 'credentials', 'credibility',
    'crescendo', 'criticize', 'crocodile', 'crossbeam', 'crossbill',
    'crossroads', 'crossword', 'crustacean', 'crystalline', 'crystallize',
    'culmination', 'cultivation', 'curiosity', 'curriculum', 'custodian',
    'customary', 'dalmatian', 'dandelion', 'dangerous', 'dashboard',
    'deactivate', 'dealership', 'decathlon', 'deceptively', 'deciduous',
    'declaration', 'decoration', 'decorative', 'decorator', 'dedicated',
    'dedication', 'defendant', 'deficiency', 'definitely', 'definition',
    'degradation', 'deliberate', 'deliberation', 'delicatessen',
    'delightful', 'delinquent', 'delphinium', 'democracy', 'demolition',
    'demonstrate', 'departure', 'dependable', 'dependence', 'dependent',
    'deployment', 'descendant', 'description', 'descriptive', 'designation',
    'desirable', 'desperate', 'desperation', 'destination', 'destruction',
    'destructive', 'detection', 'detective', 'deteriorate', 'determined',
    'deterrence', 'detrimental', 'devastating', 'developing', 'development',
    'deviation', 'diagnosis', 'diagnostics', 'dictatorship', 'dictionary',
    'difference', 'different', 'difficult', 'difficulty', 'digestion',
    'diligence', 'dimension', 'diminishing', 'diminutive', 'diplomatic',
    'direction', 'directional', 'directory', 'disability', 'disadvantage',
    'disagreeable', 'disagreement', 'disappear', 'disappoint', 'disapproval',
    'disastrous', 'discipline', 'disclosures', 'discomfort', 'disconnected',
    'discontented', 'discovery', 'discrepancy', 'discretion', 'discussion',
    'disgraceful', 'disinfectant', 'dislocation', 'disobedience',
    'disorganized', 'dispatcher', 'dispenser', 'displacement', 'disposition',
    'disqualified', 'disruption', 'dissatisfied', 'dissertation',
    'dissolution', 'distinction', 'distinctive', 'distinguish',
    'distortions', 'distraction', 'distribute', 'distribution',
    'disturbance', 'diversified', 'diversion', 'documentary', 'domesticated',
    'domination', 'doorframe', 'dormitories', 'downhearted', 'downloading',
    'draftsman', 'dragonfly', 'drainpipe', 'draughtsman', 'drawbridge',
    'dressmaker', 'dressmaking', 'drunkenness', 'duplicate', 'duplication',
    'durability', 'earthenware', 'earthquake', 'eccentric', 'eccentricity',
    'ecologically', 'economical', 'economist', 'ecosystem', 'editorial',
    'education', 'educational', 'effective', 'effervescent', 'efficiency',
    'efficient', 'effortlessly', 'elaboration', 'elasticity', 'elderberry',
    'electorate', 'electrical', 'electrician', 'electricity', 'electronics',
    'elementary', 'elevation', 'eliminate', 'elimination', 'elsewhere',
    'embankment', 'embarkation', 'embarrass', 'embroidered', 'embroidery',
    'emergence', 'emergency', 'emotional', 'empathetic', 'emphasize',
    'employment', 'empowerment', 'enchantment', 'encourage', 'encyclopedia',
    'endangered', 'endeavor', 'endorsement', 'endurance', 'energetic',
    'enforcement', 'engagement', 'engraving', 'enhancement', 'enjoyment',
    'enlargement', 'enlightened', 'enrichment', 'enrollment', 'enterprising',
    'entertainer', 'entertaining', 'enthusiasm', 'enthusiastic',
    'entitlement', 'entrepreneur', 'environment', 'equestrian',
    'equilibrium', 'equipment', 'equivalence', 'equivalent', 'eradication',
    'escalator', 'especially', 'essential', 'established', 'estimation',
    'eucalyptus', 'evaluation', 'evaporate', 'evergreen', 'everlasting',
    'evolution', 'exaggerate', 'examination', 'excavation', 'exceedingly',
    'excellence', 'excellent', 'exception', 'exceptional', 'excessive',
    'exchangeable', 'excitement', 'exclamation', 'exclusive', 'excursion',
    'execution', 'executive', 'exemplified', 'exemption', 'exhausted',
    'exhausting', 'exhibition', 'exhibitor', 'exhilarate', 'existence',
    'expansion', 'expectantly', 'expectation', 'expedition', 'expenditure',
    'expensive', 'experience', 'experiment', 'experimental', 'explanation',
    'exploration', 'explosive', 'expression', 'extension', 'extensive',
    'extinction', 'extinguish', 'extraction', 'extravagance', 'extravagant',
    'extremely', 'extremities', 'exuberance', 'eyeglasses', 'fabrication',
    'facilitate', 'fairytale', 'familiar', 'familiarity', 'fantastic',
    'fascinate', 'fascinating', 'fascination', 'fashionable', 'fatherhood',
    'favourably', 'favourite', 'feasibility', 'february', 'federation',
    'fellowship', 'fermentation', 'ferocious', 'ferryboat', 'fertilizer',
    'festivities', 'fictional', 'fictitious', 'finalizing', 'financial',
    'financier', 'fingernail', 'fingerprint', 'firefighter', 'fireplace',
    'fireproofing', 'fisherman', 'flagstone', 'flashlight', 'flavourful',
    'flexibility', 'floodplain', 'floorboard', 'flourishing', 'flowerpot',
    'fluctuation', 'fluorescent', 'footbridge', 'foreground', 'foreseeable',
    'forgetful', 'forgiveness', 'formalities', 'formation', 'formidable',
    'formulation', 'forthcoming', 'fortnight', 'fortunate', 'foundation',
    'fractional', 'framework', 'fraternity', 'freelance', 'frequency',
    'frequently', 'friendliness', 'frightening', 'frostbite', 'frostbitten',
    'frustration', 'fulfilment', 'functional', 'fundamental', 'funicular',
    'furniture', 'furthermore', 'gangplank', 'generalize', 'generation',
    'generator', 'generosity', 'geographical', 'geography', 'geologist',
    'geometrical', 'geothermal', 'germinate', 'germination', 'gigantic',
    'gingerbread', 'gladiolus', 'glamorous', 'glassblower', 'glassblowing',
    'glassware', 'goldfinch', 'goldsmith', 'gooseberry', 'governance',
    'governess', 'government', 'graduation', 'grammatical', 'grandiose',
    'grandparent', 'grandstand', 'grapefruit', 'graphically', 'grasshopper',
    'gratifying', 'gratitude', 'gravitation', 'greengage', 'greenhouse',
    'greyhound', 'grievance', 'groundnut', 'groundwater', 'groundwork',
    'guarantee', 'guardianship', 'guitarist', 'gymnasium', 'gymnastics',
    'hailstone', 'hairdresser', 'hamstring', 'handcrafted', 'handkerchief',
    'handwriting', 'happened', 'harbormaster', 'harmonica', 'harmonious',
    'harpsichord', 'hazardous', 'headmaster', 'headmistress', 'headphones',
    'headquarters', 'heartbeat', 'heartbroken', 'hearthstone', 'helicopter',
    'hemisphere', 'herbivore', 'hereditary', 'hesitation', 'hibernation',
    'hierarchy', 'highlighted', 'hippopotamus', 'historian', 'historical',
    'hitchhike', 'hollyhock', 'homecoming', 'homelessness', 'homemaker',
    'honeysuckle', 'horizontal', 'horseback', 'horsepower', 'horticulture',
    'hospitable', 'hospitality', 'household', 'housekeeper', 'housekeeping',
    'hovercraft', 'humanitarian', 'humiliation', 'hummingbird', 'humorous',
    'hurricane', 'hydrangea', 'hydraulics', 'hypocrisy', 'hypothesis',
    'hypothetical', 'identical', 'identifiable', 'ignorance', 'illegible',
    'illuminate', 'illustrate', 'illustration', 'illustrator', 'imagination',
    'imaginative', 'imitation', 'immaculate', 'immediate', 'immediately',
    'immigrant', 'immigration', 'immortality', 'immovable', 'impartial',
    'impatient', 'impeccable', 'imperfection', 'implement', 'implication',
    'importance', 'important', 'impossible', 'impractical', 'impression',
    'impressive', 'imprisonment', 'improbable', 'improvement', 'impulsively',
    'inaccessible', 'inaccurate', 'inadequate', 'inadvertent',
    'incandescent', 'inclusion', 'incompatible', 'incompetence',
    'incomplete', 'inconsistent', 'incorporate', 'incorrectly', 'incredible',
    'incremental', 'independence', 'independent', 'indication',
    'indigestion', 'indignant', 'indignation', 'individual', 'industrial',
    'industrious', 'inevitable', 'inevitably', 'inexpensive', 'infection',
    'influence', 'influential', 'informant', 'information', 'ingenious',
    'ingredient', 'inhabitants', 'inheritance', 'initiative', 'injection',
    'innkeeper', 'innovation', 'innovative', 'inoculate', 'inoculation',
    'inquisitive', 'insecticide', 'insensitive', 'inseparable', 'insistence',
    'inspection', 'inspector', 'inspiration', 'installation', 'instinctive',
    'institution', 'instruction', 'instructor', 'instrument', 'instrumental',
    'insufficient', 'insulation', 'insulator', 'insurance', 'integration',
    'intellectual', 'intelligence', 'intelligent', 'intention',
    'intentional', 'interaction', 'intercepted', 'interchange',
    'interesting', 'interference', 'intermediate', 'intermission',
    'interpret', 'interrogate', 'interrupt', 'interruption', 'intersection',
    'interviewer', 'intestine', 'intolerable', 'intricate', 'introducing',
    'introduction', 'intuitively', 'invaluable', 'invention', 'inventive',
    'inventories', 'invertebrate', 'investigate', 'investigator',
    'investments', 'invigorating', 'invisible', 'invitation', 'involuntary',
    'involvement', 'iridescent', 'irrational', 'irregular', 'irrelevant',
    'irreparable', 'irresistible', 'irreversible', 'irrigation', 'irritable',
    'irritation', 'isolation', 'itinerary', 'jackfruit', 'jackrabbit',
    'jellyfish', 'journalist', 'jubilation', 'judiciary', 'judicious',
    'jurisdiction', 'justifiable', 'kaleidoscope', 'kilometer',
    'kindergarten', 'kingfisher', 'knowledge', 'kookaburra', 'laboratory',
    'labyrinth', 'lampshade', 'landholding', 'landowner', 'landscape',
    'landslide', 'language', 'lawnmower', 'leadership', 'legendary',
    'legislation', 'legislature', 'legitimacy', 'legitimate', 'librarian',
    'lieutenant', 'lifeguard', 'lightbulb', 'lighthouses', 'lightning',
    'likelihood', 'limestone', 'limitation', 'literature', 'lithograph',
    'locksmith', 'loneliness', 'longitude', 'loudspeaker', 'lumberjack',
    'luxurious', 'machinery', 'magistrate', 'magnificent', 'magnifier',
    'magnitude', 'maintenance', 'malfunction', 'management', 'manipulation',
    'mantelpiece', 'manufacture', 'manuscript', 'marketable', 'marketplace',
    'marmalade', 'marshmallow', 'marsupial', 'marvelous', 'masculine',
    'masquerade', 'masterpiece', 'mathematical', 'mathematics', 'mayonnaise',
    'meaningful', 'measurement', 'mechanical', 'medallion', 'mediation',
    'meditation', 'melancholy', 'melodrama', 'membership', 'memorable',
    'memorandum', 'memorization', 'messenger', 'metabolism', 'metalwork',
    'metaphor', 'meteorite', 'meteorology', 'meticulous', 'metropolis',
    'microbiology', 'microphone', 'microscope', 'microscopic', 'microwave',
    'middleweight', 'midsummer', 'migration', 'milkshake', 'millennium',
    'millionaire', 'millstone', 'mindfulness', 'minuscule', 'miraculous',
    'mischievous', 'miserable', 'misfortune', 'misleading', 'mispronounce',
    'mistletoe', 'mockingbird', 'modification', 'momentous', 'monitoring',
    'monologue', 'monotonous', 'monumental', 'motionless', 'motivation',
    'motorcycle', 'mountain', 'mountainous', 'mousetrap', 'mouthpiece',
    'multitudes', 'municipal', 'muscle', 'mysterious', 'mythological',
    'narrative', 'nasturtium', 'nationality', 'naturalist', 'naturalized',
    'navigation', 'navigator', 'necessary', 'nectarine', 'negotiate',
    'negotiation', 'negotiator', 'nervousness', 'neurological',
    'nevertheless', 'newsletter', 'newspaper', 'newsprint', 'newsstand',
    'nightfall', 'nightingale', 'nocturnal', 'nomination', 'nonchalant',
    'nonetheless', 'noticeable', 'notification', 'notorious', 'numerator',
    'nutrition', 'nutritional', 'nutritious', 'obedience', 'obedient',
    'objection', 'objective', 'objectivity', 'obligation', 'observant',
    'observation', 'observatory', 'obstacle', 'obstruction', 'obtainable',
    'occasion', 'occasional', 'occasionally', 'occupation', 'occurred',
    'occurrence', 'offensive', 'operational', 'opportunity', 'opposition',
    'oppression', 'optimistic', 'orangutan', 'orchestra', 'orchestral',
    'organizer', 'orientation', 'ornamental', 'outbuilding', 'outrageous',
    'outstanding', 'overachiever', 'overcrowded', 'overflowing',
    'overhauling', 'overlapping', 'overnight', 'overpowering', 'overshadow',
    'overwhelm', 'oxidation', 'paddleboat', 'pageantry', 'painstaking',
    'paintbrush', 'paleontology', 'pantomime', 'paperback', 'paperclip',
    'papermaking', 'parachute', 'parallel', 'paralysis', 'paramedic',
    'paraphrasing', 'parliament', 'participate', 'particular', 'partition',
    'partnership', 'partridge', 'passageway', 'passionate', 'pathfinder',
    'patriotism', 'peculiar', 'pedestrian', 'penetrate', 'pentathlon',
    'penthouse', 'pepperoni', 'perception', 'percussion', 'performance',
    'performer', 'peripheral', 'periscope', 'periwinkle', 'permafrost',
    'permanent', 'permissible', 'permission', 'perpetual', 'perseverance',
    'persimmon', 'persistence', 'persistent', 'personality', 'personally',
    'personnel', 'perspective', 'persuade', 'persuasion', 'persuasive',
    'pessimistic', 'petroleum', 'pharmacist', 'phenomenal', 'philanthropy',
    'philosopher', 'philosophy', 'photocopier', 'photograph', 'physician',
    'physicist', 'physiology', 'picnicking', 'pictorial', 'picturesque',
    'pigeonhole', 'pilgrimage', 'pineapple', 'pistachio', 'pitchfork',
    'placement', 'plagiarize', 'planetarium', 'planetary', 'plantation',
    'plausible', 'playfulness', 'playground', 'playwright', 'playwriting',
    'pneumatic', 'pneumonia', 'poinsettia', 'poisonous', 'politically',
    'politician', 'pollination', 'pollution', 'pomegranate', 'popularity',
    'population', 'porcelain', 'porcupine', 'possession', 'possibility',
    'postmaster', 'postponement', 'potentially', 'practically',
    'practitioner', 'precaution', 'precious', 'predecessor', 'predicament',
    'predictable', 'prediction', 'preferable', 'preference', 'prehistoric',
    'prejudice', 'preliminary', 'premature', 'preparation', 'preposterous',
    'prescription', 'presentable', 'presentation', 'presenter',
    'preservation', 'presidency', 'president', 'prestigious', 'presumably',
    'prevalent', 'prevention', 'priceless', 'primitive', 'principal',
    'principle', 'privilege', 'probability', 'procedure', 'proceedings',
    'processions', 'proclamation', 'production', 'productive',
    'productivity', 'professional', 'professor', 'proficiency', 'proficient',
    'profitable', 'programmer', 'programming', 'progression', 'prohibition',
    'projection', 'projector', 'prominent', 'promotion', 'promotional',
    'pronounce', 'proofreading', 'propaganda', 'propeller', 'properties',
    'proportion', 'proportional', 'proposition', 'proprietor', 'prosecution',
    'prospective', 'prosperity', 'prosperous', 'protagonist', 'protection',
    'protective', 'protester', 'provincial', 'provision', 'provisional',
    'psychology', 'publication', 'publicity', 'publisher', 'punctuality',
    'punctuation', 'purposeful', 'purposeless', 'quantity', 'quarantine',
    'quarrelsome', 'quarterback', 'question', 'questionable', 'quotation',
    'racecourse', 'radiation', 'radiographer', 'rainwater', 'randomness',
    'raspberry', 'rattlesnake', 'readability', 'realignment', 'realistic',
    'realization', 'reasonable', 'reasonably', 'reassemble', 'reassurance',
    'rebelliously', 'recalculate', 'receptacle', 'receptionist',
    'recharging', 'recognition', 'recognizable', 'recollection', 'recommend',
    'reconciling', 'reconsider', 'reconstruct', 'recreational',
    'recruitment', 'rectangular', 'recuperate', 'redirection', 'reduction',
    'redundancy', 'reestablish', 'reference', 'reflection', 'reflectively',
    'reformation', 'refraction', 'refreshing', 'refreshment', 'refrigerate',
    'refrigerator', 'regeneration', 'registrar', 'registration',
    'regrettable', 'regularity', 'regulation', 'regulator', 'rehabilitate',
    'rehearsal', 'reinstated', 'rejection', 'rejoicing', 'relationship',
    'relaxation', 'relentless', 'reliability', 'religious', 'reluctant',
    'remarkable', 'remembrance', 'reminiscent', 'remoteness', 'renaissance',
    'renovation', 'reorganize', 'repayments', 'repertoire', 'repetition',
    'repetitive', 'replacement', 'replenished', 'reportedly', 'reprimanded',
    'reproduction', 'republican', 'reputation', 'requirement', 'resemblance',
    'reservation', 'reservoir', 'residential', 'resignation', 'resilient',
    'resistance', 'resolution', 'resonance', 'resourceful', 'respectable',
    'respiration', 'responsible', 'restaurant', 'restlessness',
    'restoration', 'restriction', 'retirement', 'revelation', 'reversible',
    'rhinoceros', 'rhododendron', 'rhythm', 'ridiculous', 'righteous',
    'roadblocks', 'roadrunner', 'rotational', 'roundabout', 'sacrifice',
    'sacrilegious', 'safekeeping', 'sagebrush', 'salamander', 'salesperson',
    'sandpaper', 'sandpiper', 'sandstone', 'sandwich', 'satellite',
    'satisfaction', 'satisfactory', 'sauerkraut', 'saxophone', 'scandalous',
    'scarecrow', 'scholarship', 'schoolhouse', 'scientific', 'scientist',
    'scintillate', 'scissors', 'scoreboard', 'screenplay', 'screwdriver',
    'scrumptious', 'scrupulous', 'sculptural', 'sculpture', 'seamstress',
    'searchlight', 'secondary', 'secretarial', 'secretary', 'secretive',
    'selection', 'selectively', 'semicircle', 'sensational', 'sensitive',
    'sensitivity', 'sentimental', 'separate', 'separation', 'settlement',
    'shareholder', 'shipbuilding', 'shipwright', 'shoemakers', 'shopkeeper',
    'shoreline', 'shortbread', 'shortcoming', 'shortsighted', 'showmanship',
    'sightseeing', 'signalman', 'significance', 'significant', 'silhouette',
    'similarity', 'simplicity', 'simplified', 'simulation', 'simultaneous',
    'sincere', 'sincerely', 'sincerity', 'situation', 'situational',
    'skateboard', 'sketchbook', 'skyscraper', 'smokestack', 'snapdragon',
    'snowdrift', 'snowmobile', 'soapstone', 'socialize', 'sociologist',
    'solicitor', 'solidarity', 'soliloquy', 'solitariness', 'sometimes',
    'soothingly', 'sophisticate', 'sophomore', 'sorrowfully', 'soundtrack',
    'sourdough', 'souvenir', 'spaghetti', 'specialist', 'specialize',
    'spectacles', 'spectacular', 'spectator', 'speculation', 'speedboat',
    'spellbound', 'spiritual', 'spirituality', 'spokesperson', 'sponsorship',
    'spontaneous', 'sportsman', 'spotlight', 'spreadsheet', 'springtime',
    'sprinkler', 'sprinting', 'stabilizer', 'stagecoach', 'stagecraft',
    'staggering', 'staircase', 'stakeholder', 'stalactite', 'stalagmite',
    'standardize', 'statement', 'statesman', 'stationary', 'stationery',
    'statistical', 'statistician', 'statistics', 'statuette', 'steadfastly',
    'steamship', 'stepladder', 'stereotype', 'stethoscope', 'stimulating',
    'stimulation', 'stonemason', 'stonework', 'stopwatch', 'storekeeper',
    'storeroom', 'storybook', 'storyteller', 'straightaway', 'straightened',
    'strategic', 'stratosphere', 'strawberry', 'streamlined', 'strength',
    'strengthen', 'strenuous', 'stretcher', 'stringently', 'structural',
    'stubbornness', 'studiously', 'stupendous', 'stylishness', 'submarine',
    'subscription', 'subsequently', 'substantial', 'subtraction',
    'successful', 'sufficient', 'sugarcane', 'suggestion', 'summarized',
    'sunflower', 'superhuman', 'superiority', 'supermarket', 'supernatural',
    'supersede', 'superstition', 'supervision', 'supervisor', 'supplement',
    'supporter', 'supportive', 'supposedly', 'surprise', 'surrendered',
    'surroundings', 'surveillance', 'survivable', 'suspenseful',
    'suspension', 'suspicious', 'sustainable', 'swiftness', 'swordfish',
    'symbolize', 'symmetrical', 'sympathetic', 'symphony', 'synchronize',
    'systematic', 'tablecloth', 'tablespoon', 'tambourine', 'tangerine',
    'tantalizing', 'tarantula', 'technical', 'technician', 'telegraphic',
    'telephones', 'television', 'temperament', 'temperate', 'temperature',
    'temporarily', 'temporary', 'temptation', 'tenacious', 'tentative',
    'termination', 'terracotta', 'terrestrial', 'territorial', 'territory',
    'testimony', 'thanksgiving', 'theatrical', 'theoretical', 'therapist',
    'thereafter', 'therefore', 'thermometer', 'thesaurus', 'thoroughbred',
    'thoroughfare', 'thoughtful', 'threadbare', 'threatening', 'threefold',
    'thrilling', 'thumbprint', 'thunderbolt', 'thunderous', 'timekeeper',
    'timelessness', 'timepiece', 'timetable', 'toadstool', 'tobogganing',
    'tolerable', 'tolerance', 'tollbooth', 'tomorrow', 'toothache',
    'torchlight', 'tournament', 'townspeople', 'trademarked', 'tradesman',
    'traditional', 'trafficking', 'trailblazer', 'trampoline', 'tranquility',
    'transaction', 'transition', 'translation', 'translator', 'transmission',
    'transparency', 'transparent', 'transplanted', 'transported',
    'treacherous', 'treadmill', 'treasurer', 'tremendous', 'triangular',
    'tributary', 'triumphant', 'tropicbird', 'troublesome', 'trustworthy',
    'truthfully', 'turbulence', 'turnstile', 'twilight', 'typewriter',
    'ultraviolet', 'umbrella', 'unaccustomed', 'unanimous', 'unavoidable',
    'unbalanced', 'unbearable', 'unbearably', 'unbeatable', 'unbelievable',
    'unbreakable', 'uncertainty', 'uncommonly', 'uncompleted', 'unconcerned',
    'unconscious', 'underground', 'underneath', 'understand', 'undertaker',
    'undertaking', 'underwater', 'undoubtedly', 'unexpected', 'unexplained',
    'unfamiliar', 'unfortunate', 'unfriendly', 'ungrateful', 'unhappiness',
    'unhealthy', 'unidentified', 'unimaginable', 'unimportant', 'universal',
    'university', 'unlimited', 'unnatural', 'unnecessary', 'unnoticeable',
    'unoccupied', 'unofficial', 'unpleasant', 'unprepared', 'unprofitable',
    'unreachable', 'unrealistic', 'unreasonable', 'unrecognized',
    'unreliable', 'unsatisfied', 'unspeakable', 'unsuccessful', 'unsuitable',
    'unsupported', 'unsurpassed', 'upholsterer', 'upholstery', 'uppermost',
    'vaccination', 'vacuum', 'valuation', 'variability', 'variation',
    'vaudeville', 'vegetable', 'vegetarian', 'vegetation', 'vehemently',
    'venerable', 'vengeance', 'ventilation', 'ventilator', 'verification',
    'versatile', 'versatility', 'vertebrate', 'veterinarian', 'veterinary',
    'victorious', 'viewpoints', 'villainous', 'vinaigrette', 'violinist',
    'visibility', 'vivacious', 'vocabulary', 'volleyball', 'voluntary',
    'volunteer', 'vulnerable', 'wallpaper', 'warehouse', 'washbasin',
    'watchmaker', 'watercress', 'waterfront', 'watermelon', 'waterproof',
    'watershed', 'watertight', 'waterwheel', 'wavelength', 'weatherproof',
    'wednesday', 'welcoming', 'wheelbarrow', 'wheelwright', 'whetstone',
    'whimsically', 'whirlpool', 'wholesaler', 'widespread', 'wilderness',
    'willingness', 'windowpane', 'windowsill', 'windshield', 'windstorm',
    'wintertime', 'withdrawal', 'withdrawing', 'withstanding', 'witnessing',
    'wolverine', 'wonderful', 'woodcarver', 'woodcarving', 'woodlouse',
    'woodpecker', 'workbench', 'workforce', 'workmanship', 'worshipping',
    'worthiness', 'worthwhile', 'wrestling', 'wretchedness', 'wristwatch',
    'xylophone', 'yellowhammer', 'yesterday',
  ],
];

/**
 * Common English words that are NOT in the shipped tiers but that a one-edit
 * mutation could accidentally form ("two" -> "tow", "form" -> "from"). A fake
 * that lands on any of these would punish a correct read, so the generator
 * rejects against VALID ∪ this guard, not VALID alone.
 */
const COMMON_GUARD = [
  'a', 'an', 'as', 'at', 'be', 'by', 'do', 'go', 'he', 'if', 'in', 'is',
  'it', 'me', 'my', 'no', 'of', 'on', 'or', 'so', 'to', 'up', 'us', 'we',
  'act', 'add', 'age', 'ago', 'aid', 'aim', 'air', 'all', 'and', 'ant',
  'any', 'ape', 'apt', 'arc', 'are', 'art', 'ate', 'axe', 'bad', 'bag',
  'ban', 'bar', 'bat', 'bay', 'bee', 'beg', 'bet', 'bid', 'bin', 'bit',
  'boa', 'bog', 'bow', 'boy', 'bud', 'bug', 'bun', 'but', 'buy', 'cab',
  'can', 'cap', 'cod', 'cog', 'con', 'cop', 'cot', 'cow', 'coy', 'cry',
  'cub', 'cue', 'cut', 'dam', 'den', 'dew', 'did', 'die', 'dig', 'dim',
  'din', 'dip', 'doe', 'dot', 'dip', 'due', 'dug', 'dun', 'dye', 'ear',
  'eel', 'ebb', 'eid', 'eke', 'elf', 'elk', 'elm', 'era', 'eve', 'eye', 'fan',
  'far', 'fat', 'fax', 'fed', 'fee', 'few', 'fig', 'fin', 'fit', 'fix',
  'flu', 'fly', 'foe', 'fog', 'for', 'fox', 'fry', 'gap', 'gas', 'gel',
  'gem', 'get', 'gig', 'gin', 'got', 'gum', 'gun', 'gut', 'guy', 'gym',
  'had', 'ham', 'has', 'hay', 'hen', 'her', 'hew', 'hey', 'hid', 'him',
  'hip', 'his', 'hit', 'hoe', 'hog', 'hop', 'how', 'hub', 'hue', 'hug',
  'hum', 'hut', 'ill', 'imp', 'ink', 'inn', 'ion', 'ire', 'irk', 'its',
  'ivy', 'jab', 'jam', 'jar', 'jaw', 'jay', 'jet', 'jig', 'jog', 'jot',
  'joy', 'jug', 'keg', 'kid', 'kin', 'kit', 'lab', 'lad', 'lag', 'lap',
  'law', 'lay', 'lea', 'led', 'lee', 'let', 'lid', 'lie', 'lip', 'lit',
  'lob', 'log', 'lot', 'low', 'mad', 'man', 'mat', 'maw', 'may', 'men',
  'met', 'mid', 'mix', 'mob', 'mop', 'mow', 'mud', 'mug', 'nab', 'nag',
  'nap', 'net', 'nub', 'net', 'nil', 'nip', 'nit', 'nod', 'nor', 'not',
  'now', 'nun', 'nut', 'oak', 'oar', 'oat', 'odd', 'ode', 'off', 'oft',
  'oil', 'one', 'opt', 'orb', 'ore', 'our', 'out', 'owe', 'owl', 'own',
  'pad', 'pal', 'pan', 'par', 'pat', 'paw', 'pay', 'pea', 'peg', 'pet',
  'pie', 'pig', 'pin', 'pit', 'ply', 'pod', 'pop', 'pot', 'pro', 'pry',
  'pub', 'pun', 'pup', 'put', 'rag', 'ram', 'ran', 'rap', 'rat', 'raw',
  'ray', 'rib', 'rid', 'rig', 'rim', 'rip', 'rob', 'rod', 'roe', 'rot',
  'row', 'rub', 'rue', 'rug', 'rum', 'rut', 'rye', 'sad', 'sag', 'sap',
  'sat', 'saw', 'say', 'set', 'sew', 'she', 'shy', 'sin', 'sip', 'sir',
  'ski', 'sly', 'sob', 'sod', 'son', 'sow', 'soy', 'spa', 'spy', 'sty',
  'sub', 'sue', 'sum', 'tab', 'tag', 'tan', 'tap', 'tar', 'tax', 'the',
  'thy', 'tie', 'tin', 'tip', 'toe', 'ton', 'too', 'tot', 'tow', 'toy',
  'try', 'tub', 'tug', 'two', 'urn', 'use', 'van', 'vat', 'vet', 'via',
  'vie', 'vow', 'wag', 'war', 'was', 'wax', 'way', 'web', 'wed', 'wee',
  'who', 'why', 'wig', 'wit', 'woe', 'won', 'woo', 'wry', 'yak', 'yam',
  'yap', 'yaw', 'yet', 'yew', 'you', 'zap', 'zoo',
  'ability', 'able', 'about', 'above', 'accept', 'across', 'action',
  'after', 'again', 'agree', 'ahead', 'alive', 'alone', 'along', 'also',
  'always', 'among', 'angle', 'anger', 'angry', 'answer', 'apple', 'area',
  'argue', 'arrow', 'aside', 'attack', 'aunt', 'autumn', 'awake', 'away',
  'back', 'ball', 'band', 'bank', 'base', 'bath', 'beach', 'bean', 'beat',
  'been', 'beer', 'bell', 'belt', 'bend', 'best', 'bird', 'bite', 'black',
  'blade', 'blame', 'blank', 'blind', 'block', 'blood', 'blow', 'blue',
  'board', 'boat', 'body', 'boil', 'bold', 'bone', 'book', 'boot', 'born',
  'boss', 'both', 'bowl', 'brain', 'brand', 'brave', 'break', 'brick',
  'bring', 'broad', 'broke', 'brown', 'brush', 'build', 'burn', 'burst',
  'busy', 'cake', 'call', 'calm', 'came', 'camp', 'card', 'care', 'cart',
  'case', 'cash', 'cast', 'cave', 'cell', 'cent', 'chain', 'chalk',
  'charm', 'chart', 'chase', 'cheap', 'check', 'cheese', 'chest', 'chief',
  'child', 'chin', 'chip', 'choice', 'city', 'claim', 'class', 'clay',
  'clean', 'clear', 'climb', 'cling', 'close', 'cloth', 'club', 'coach',
  'coal', 'coast', 'coat', 'code', 'cold', 'come', 'cook', 'cool', 'cope',
  'copy', 'cord', 'core', 'corn', 'cost', 'count', 'court', 'cover',
  'crack', 'craft', 'crash', 'cream', 'crew', 'crime', 'crop', 'cross',
  'crowd', 'crown', 'cure', 'curl', 'curve', 'dare', 'dark', 'data',
  'date', 'dawn', 'dead', 'deal', 'dear', 'debt', 'deck', 'deep', 'deer',
  'depth', 'dirt', 'dish', 'dive', 'done', 'doubt', 'down', 'dozen',
  'draft', 'drag', 'drain', 'draw', 'dress', 'drew', 'drift', 'drink',
  'drive', 'drop', 'drum', 'duck', 'dull', 'dust', 'duty', 'each',
  'early', 'earn', 'earth', 'ease', 'east', 'easy', 'edge', 'eight',
  'either', 'else', 'empty', 'enemy', 'enjoy', 'enter', 'equal', 'even',
  'event', 'ever', 'every', 'exact', 'exit', 'extra', 'face', 'fact',
  'fade', 'fail', 'fair', 'faith', 'fall', 'false', 'fame', 'farm',
  'fate', 'fault', 'fear', 'feed', 'feel', 'fell', 'felt', 'fence',
  'field', 'fifth', 'fight', 'file', 'fill', 'film', 'final', 'find',
  'fine', 'firm', 'first', 'five', 'flag', 'flame', 'flash', 'flat',
  'flesh', 'float', 'flood', 'floor', 'flow', 'fold', 'folk', 'food',
  'foot', 'force', 'fork', 'form', 'fort', 'forth', 'found', 'four',
  'frame', 'free', 'fresh', 'from', 'front', 'frost', 'fruit', 'fuel',
  'full', 'fund', 'gain', 'gate', 'gave', 'gear', 'gift', 'girl', 'give',
  'glad', 'globe', 'glory', 'glove', 'glow', 'goal', 'goat', 'gone',
  'good', 'grace', 'grade', 'grain', 'grand', 'grant', 'grass', 'grave',
  'gray', 'great', 'grew', 'grey', 'grip', 'group', 'grow', 'guard',
  'guess', 'guest', 'guide', 'hair', 'half', 'hall', 'halt', 'hang',
  'hard', 'harm', 'have', 'head', 'heal', 'heap', 'hear', 'heart', 'heat',
  'heavy', 'heel', 'held', 'hell', 'help', 'here', 'hero', 'hide', 'high',
  'hill', 'hint', 'hire', 'hold', 'hole', 'holy', 'home', 'honey', 'hook',
  'hope', 'horn', 'horse', 'host', 'hour', 'huge', 'hunt', 'hurt', 'idea',
  'inch', 'into', 'iron', 'item', 'join', 'joint', 'joke', 'judge',
  'juice', 'just', 'keen', 'keep', 'kept', 'kick', 'kill', 'kind', 'knee',
  'knew', 'knife', 'knock', 'known', 'lace', 'lack', 'lady', 'laid',
  'lake', 'land', 'lane', 'large', 'last', 'late', 'laugh', 'lawn',
  'lead', 'lean', 'leap', 'learn', 'least', 'leave', 'left', 'lend',
  'less', 'level', 'lift', 'like', 'limb', 'limit', 'line', 'link',
  'lion', 'list', 'live', 'load', 'loaf', 'loan', 'local', 'lock',
  'lodge', 'lone', 'long', 'look', 'loop', 'loose', 'lord', 'lose',
  'loss', 'lost', 'loud', 'love', 'luck', 'lunch', 'lung', 'made', 'mail',
  'main', 'make', 'male', 'many', 'march', 'mark', 'mass', 'match',
  'mate', 'math', 'meal', 'mean', 'meat', 'meet', 'melt', 'mend', 'mere',
  'mess', 'might', 'mild', 'mile', 'mill', 'mind', 'mine', 'miss', 'mist',
  'mode', 'more', 'most', 'moth', 'mount', 'mouse', 'mouth', 'move',
  'much', 'must', 'nail', 'name', 'near', 'neat', 'neck', 'need', 'nest',
  'news', 'next', 'nice', 'nine', 'noble', 'noise', 'none', 'noon',
  'north', 'nose', 'note', 'noun', 'nurse', 'obey', 'ocean', 'offer',
  'often', 'once', 'only', 'onto', 'open', 'order', 'other', 'ought',
  'ounce', 'oven', 'over', 'pace', 'pack', 'page', 'paid', 'pain',
  'paint', 'pair', 'pale', 'palm', 'pant', 'park', 'part', 'pass',
  'past', 'path', 'peace', 'peak', 'pearl', 'pick', 'piece', 'pile',
  'pine', 'pink', 'pipe', 'pitch', 'place', 'plain', 'plan', 'plate',
  'play', 'plot', 'poem', 'point', 'pole', 'pond', 'pool', 'poor',
  'port', 'pose', 'post', 'pour', 'power', 'press', 'price', 'pride',
  'prime', 'print', 'prize', 'proof', 'proud', 'prove', 'pull', 'pump',
  'pure', 'push', 'quit', 'quite', 'race', 'rack', 'rage', 'raise',
  'range', 'rank', 'rapid', 'rare', 'rate', 'reach', 'read', 'ready',
  'real', 'rear', 'rent', 'rest', 'rice', 'rich', 'ride', 'rise', 'risk',
  'roar', 'roast', 'roll', 'roof', 'room', 'root', 'rope', 'rose',
  'rough', 'round', 'route', 'royal', 'rude', 'rule', 'rush', 'rust',
  'safe', 'sail', 'sake', 'sale', 'salt', 'same', 'save', 'scale',
  'scare', 'scene', 'scope', 'score', 'seal', 'seat', 'seed', 'seek',
  'seem', 'seen', 'self', 'sell', 'send', 'sense', 'sent', 'serve',
  'seven', 'shade', 'shake', 'shall', 'shame', 'shape', 'share', 'shed',
  'sheep', 'sheet', 'shelf', 'shell', 'shift', 'shine', 'shirt', 'shock',
  'shoe', 'shook', 'shoot', 'shop', 'shore', 'short', 'shot', 'shout',
  'show', 'shut', 'sick', 'side', 'sigh', 'sight', 'sign', 'silk',
  'since', 'sing', 'sink', 'site', 'size', 'skill', 'skin', 'skirt',
  'slave', 'slid', 'slide', 'slip', 'slope', 'slow', 'small', 'smart',
  'smell', 'smoke', 'snake', 'soap', 'sock', 'soft', 'soil', 'sold',
  'sole', 'solid', 'solve', 'some', 'soon', 'sore', 'sorry', 'sort',
  'soul', 'south', 'speak', 'speed', 'spell', 'spend', 'spent', 'spin',
  'spite', 'split', 'spoke', 'sport', 'spot', 'spray', 'spread', 'stab',
  'staff', 'stage', 'stair', 'stake', 'stamp', 'stand', 'stare', 'start',
  'state', 'stay', 'steal', 'steam', 'steel', 'steep', 'steer', 'stem',
  'step', 'stick', 'stiff', 'still', 'stock', 'stole', 'stone', 'stood',
  'stop', 'store', 'storm', 'stove', 'strap', 'straw', 'strip', 'stuck',
  'study', 'stuff', 'style', 'such', 'suit', 'sure', 'sweep', 'sweet',
  'swim', 'swing', 'sword', 'take', 'tale', 'talk', 'tall', 'tank',
  'tape', 'task', 'taste', 'teach', 'team', 'tear', 'tell', 'tend',
  'tent', 'term', 'test', 'text', 'than', 'that', 'them', 'then', 'there',
  'these', 'they', 'thick', 'thin', 'thing', 'think', 'third', 'this',
  'those', 'three', 'threw', 'throw', 'thumb', 'thus', 'tide', 'tidy',
  'tight', 'till', 'tilt', 'tiny', 'tire', 'title', 'today', 'told',
  'tone', 'tool', 'tooth', 'total', 'touch', 'tough', 'tour', 'toward',
  'tower', 'town', 'trace', 'track', 'trade', 'trail', 'train', 'trap',
  'tray', 'treat', 'trend', 'trial', 'tribe', 'trick', 'trim', 'trip',
  'truck', 'true', 'trunk', 'trust', 'truth', 'tube', 'tune', 'turn',
  'twin', 'twist', 'type', 'uncle', 'under', 'union', 'unit', 'until',
  'upon', 'upper', 'urge', 'used', 'user', 'usual', 'value', 'verb',
  'verse', 'very', 'view', 'visit', 'vital', 'vote', 'wage', 'wait',
  'wake', 'walk', 'want', 'ward', 'warm', 'warn', 'wash', 'waste',
  'watch', 'wear', 'week', 'well', 'went', 'were', 'west', 'what',
  'wheat', 'wheel', 'when', 'where', 'which', 'while', 'whip', 'whole',
  'whom', 'whose', 'wide', 'wife', 'wild', 'will', 'wine', 'wing',
  'wipe', 'wire', 'wise', 'wish', 'with', 'woke', 'woman', 'wood',
  'wool', 'wore', 'work', 'worm', 'worn', 'worry', 'worse', 'worst',
  'worth', 'would', 'wound', 'wrap', 'wrist', 'write', 'wrong', 'wrote',
  'yard', 'yarn', 'year', 'yell', 'young', 'your', 'youth', 'zero',
  'zone',
];

/** Every shipped, playable word. Order: tier by tier, list order. */
export const ALL_WORDS = TIERS.flat();

/** Validity set for gameplay: the shipped tiers. */
const VALID = new Set(ALL_WORDS);

/** Rejection set for the fake generator: shipped words ∪ common guard. */
const GUARD = new Set([...ALL_WORDS, ...COMMON_GUARD, ...EXTENDED_GUARD]);

/**
 * The validity checker the acceptance gate names: a real (shipped) word must
 * NEVER be rejected. Case- and whitespace-forgiving so no UI plumbing can
 * manufacture a false negative.
 */
export function isValidWord(word) {
  return VALID.has(String(word ?? '').trim().toLowerCase());
}

export function tierCount() { return TIERS.length; }

/** Words available at a tier (clamped, so a too-high tier never throws). */
export function tierWords(tier) {
  const t = Math.max(0, Math.min(TIERS.length - 1, tier | 0));
  return TIERS[t];
}

/** Deterministically pick one real word from a tier. */
export function pickWord(tier, rand) {
  const words = tierWords(tier);
  return words[Math.floor(rand() * words.length) % words.length];
}

const gcd = (a, b) => (b === 0 ? a : gcd(b, a % b));

/**
 * The no-repeat draw (Phase 9): the k-th word of a seeded coprime walk
 * through a tier. `rand` must be a FRESH rng seeded per (run, tier) — two
 * draws fix the walk's offset and stride — so for a given lane every k maps
 * to a distinct word until the whole tier cycles (940-2,200 words: longer
 * than any run's stay in a tier). Kills both back-to-back duplicates and
 * the birthday-problem repeats a uniform draw guarantees.
 */
export function pickWordCycle(tier, k, rand) {
  const words = tierWords(tier);
  const n = words.length;
  const offset = Math.floor(rand() * n) % n;
  let stride = 1 + (Math.floor(rand() * (n - 1)) % (n - 1));
  while (gcd(stride, n) !== 1) stride = (stride % (n - 1)) + 1;
  return words[(offset + (k % n) * stride) % n];
}

const VOWELS = 'aeiou';

/** The mutation strategies, all one honest "misread" away from the source. */
const MUTATIONS = [
  // Swap two adjacent letters: recieve.
  (w, i) => (i < w.length - 1 && w[i] !== w[i + 1]
    ? w.slice(0, i) + w[i + 1] + w[i] + w.slice(i + 2) : null),
  // Double a letter: dinnner without the drama — winnter.
  (w, i) => w.slice(0, i + 1) + w[i] + w.slice(i + 1),
  // Drop a letter (never below 3 chars): begining.
  (w, i) => (w.length > 3 ? w.slice(0, i) + w.slice(i + 1) : null),
  // Substitute a vowel with a different vowel: definately.
  (w, i) => {
    const c = w[i];
    if (!VOWELS.includes(c)) return null;
    const alt = VOWELS[(VOWELS.indexOf(c) + 1 + Math.floor(i / 2)) % VOWELS.length];
    return alt === c ? null : w.slice(0, i) + alt + w.slice(i + 1);
  },
];

/**
 * Build a plausible misspelling of `word` — guaranteed to differ from the
 * source and to NOT be a recognized word (shipped list or common guard), so a
 * player who reads correctly is never punished for our generator's luck.
 *
 * Deterministic for a given (word, rand-stream). Termination is guaranteed:
 * after bounded random attempts it sweeps every mutation × position, and a
 * finite guard set cannot absorb every single-edit variant of a word.
 */
export function makeFake(word, rand) {
  const w = String(word).toLowerCase();
  // A fake must not be a real word (the player would be punished for reading
  // correctly) and must not be something a general-audience rating will not
  // carry. The second is not hypothetical: one edit reaches 'cock' from
  // 'clock', 'rape' from 'grape', 'fag' from 'flag'. tools/family-gate.mjs
  // enumerates every reachable mutation and fails the build on a hit.
  const bad = (f) => !f || f === w || GUARD.has(f) || isBlocked(f);

  for (let attempt = 0; attempt < 24; attempt++) {
    const m = MUTATIONS[Math.floor(rand() * MUTATIONS.length) % MUTATIONS.length];
    const i = Math.floor(rand() * w.length) % w.length;
    const f = m(w, i);
    if (!bad(f)) return f;
  }
  // Deterministic sweep — rand no longer consulted.
  for (const m of MUTATIONS) {
    for (let i = 0; i < w.length; i++) {
      const f = m(w, i);
      if (!bad(f)) return f;
    }
  }
  // Last resort: substitute each position with each letter until unrecognized.
  for (let i = w.length - 1; i >= 0; i--) {
    for (const c of 'zxqjkvw') {
      if (w[i] === c) continue;
      const f = w.slice(0, i) + c + w.slice(i + 1);
      if (!bad(f)) return f;
    }
  }
  return w + 'x'; // unreachable in practice; still not a guard word
}
