/**
 * DICTION DASH — standalone word-list service.
 *
 * Plain validity/difficulty-tiered word list: common, short, unambiguous words
 * at low tiers, ramping up. Deliberately built as its own module with its own
 * tests (tools/word-gates.mjs) and ZERO runtime dependencies — no runner
 * imports, no external packages — so other games can pull it in unchanged.
 * Every word is hand-curated for this game (a harvested catalog bank was
 * tried in Phase 9 and deliberately removed in Phase 11: curation beats
 * volume now that the no-repeat walk and per-attempt salt carry variety).
 *
 * Determinism contract: every function that makes a choice takes `rand`, a
 * caller-supplied () => float in [0,1). Nothing in here touches Math.random,
 * so a seeded caller always gets the same words.
 *
 * All words are lowercase a–z, no proper nouns, no hyphens or apostrophes.
 */
import { EXTENDED_GUARD } from './guard.js';

/**
 * Difficulty tiers, easiest first. Tier 0 is short + high-frequency; later
 * tiers get longer and lean into classically hard spellings, because a fake
 * only creates tension when the real spelling takes a beat to verify.
 */
export const TIERS = [
  // Tier 0 — short, everyday, unambiguous.
  [
    'act', 'add', 'age', 'ago', 'aid', 'aim', 'air', 'all', 'and', 'ant',
    'any', 'apt', 'arc', 'arm', 'art', 'ash', 'ask', 'ate', 'axe', 'bad',
    'bag', 'ban', 'bar', 'bat', 'bay', 'bed', 'bee', 'bet', 'bid', 'big',
    'bin', 'bit', 'bow', 'box', 'boy', 'bud', 'bug', 'bun', 'bus', 'buy',
    'cab', 'can', 'cap', 'car', 'cat', 'cob', 'cod', 'cog', 'cot', 'cow',
    'cry', 'cub', 'cue', 'cup', 'cut', 'dab', 'dam', 'day', 'den', 'dew',
    'dig', 'dim', 'dip', 'dog', 'dot', 'dry', 'dub', 'due', 'dug', 'ear',
    'eat', 'eel', 'egg', 'elf', 'elk', 'elm', 'end', 'era', 'eve', 'ewe',
    'eye', 'fan', 'far', 'fat', 'fed', 'fee', 'few', 'fig', 'fin', 'fit',
    'fix', 'flu', 'fly', 'foe', 'fog', 'for', 'fox', 'fry', 'fun', 'fur',
    'gap', 'gas', 'gel', 'gem', 'get', 'got', 'gum', 'gut', 'guy', 'gym',
    'had', 'ham', 'has', 'hat', 'hay', 'hem', 'hen', 'hid', 'him', 'hip',
    'hit', 'hoe', 'hog', 'hop', 'hot', 'how', 'hub', 'hue', 'hug', 'hum',
    'hut', 'ice', 'icy', 'ill', 'ink', 'inn', 'ion', 'its', 'ivy', 'jab',
    'jam', 'jar', 'jaw', 'jay', 'jet', 'jig', 'job', 'jog', 'jot', 'joy',
    'jug', 'key', 'kid', 'kin', 'kit', 'lab', 'lad', 'lag', 'lap', 'law',
    'lay', 'led', 'leg', 'let', 'lid', 'lie', 'lip', 'lit', 'lob', 'log',
    'lot', 'low', 'mad', 'man', 'map', 'mat', 'may', 'men', 'met', 'mix',
    'mob', 'mop', 'mow', 'mud', 'mug', 'nab', 'nag', 'nap', 'net', 'new',
    'nib', 'nil', 'nip', 'nod', 'nor', 'not', 'now', 'nun', 'nut', 'oak',
    'oar', 'oat', 'odd', 'off', 'oil', 'old', 'one', 'orb', 'ore', 'our',
    'out', 'owe', 'owl', 'own', 'pad', 'pan', 'par', 'pat', 'paw', 'pay',
    'pea', 'peg', 'pen', 'pet', 'pie', 'pig', 'pin', 'pit', 'pod', 'pop',
    'pot', 'pun', 'pup', 'put', 'rag', 'ram', 'ran', 'rap', 'rat', 'raw',
    'ray', 'red', 'rib', 'rid', 'rim', 'rip', 'rob', 'rod', 'rot', 'row',
    'rub', 'rug', 'run', 'rut', 'rye', 'sad', 'sag', 'sap', 'sat', 'saw',
    'say', 'sea', 'see', 'set', 'sew', 'shy', 'sip', 'sir', 'sit', 'six',
    'ski', 'sky', 'sly', 'sob', 'sod', 'son', 'sow', 'soy', 'spa', 'spy',
    'sty', 'sub', 'sue', 'sum', 'sun', 'tab', 'tag', 'tan', 'tap', 'tar',
    'tax', 'tea', 'ten', 'tie', 'tin', 'tip', 'toe', 'ton', 'too', 'top',
    'tow', 'toy', 'try', 'tub', 'tug', 'two', 'urn', 'use', 'van', 'vat',
    'vet', 'vow', 'wad', 'wag', 'war', 'was', 'wax', 'way', 'web', 'wed',
    'wet', 'who', 'why', 'wig', 'win', 'wit', 'woe', 'wok', 'won', 'woo',
    'yak', 'yam', 'yap', 'yes', 'yet', 'yew', 'zap', 'zip', 'zoo',
  ],
  // Tier 1 — common four/five-letter words.
  [
    'able', 'acid', 'apple', 'aunt', 'away', 'baby', 'back', 'bake', 'ball',
    'band', 'bank', 'barn', 'bath', 'beach', 'bead', 'beam', 'bean', 'bear',
    'beat', 'bell', 'belt', 'bend', 'berry', 'best', 'bike', 'bind', 'bird',
    'bite', 'blob', 'blue', 'boat', 'body', 'boil', 'bolt', 'bone', 'book',
    'boot', 'born', 'both', 'bowl', 'brag', 'bread', 'brick', 'brim', 'brush',
    'busy', 'cage', 'cake', 'calf', 'calm', 'camp', 'candy', 'card', 'care',
    'cart', 'case', 'cash', 'cast', 'cave', 'cent', 'chair', 'chat', 'chef',
    'chew', 'chin', 'chip', 'chop', 'city', 'clap', 'claw', 'clay', 'clip',
    'clock', 'cloud', 'club', 'clue', 'coal', 'coat', 'code', 'coin', 'cold',
    'colt', 'comb', 'cone', 'cook', 'cool', 'cope', 'copy', 'cord', 'core',
    'cork', 'corn', 'cost', 'cozy', 'crab', 'crew', 'crop', 'crow', 'crown',
    'cube', 'curb', 'cure', 'curl', 'dance', 'dare', 'dark', 'dart', 'dawn',
    'deal', 'dear', 'deck', 'deep', 'deer', 'dent', 'desk', 'dial', 'dice',
    'diet', 'dirt', 'dish', 'dive', 'dock', 'doll', 'dome', 'done', 'door',
    'dose', 'down', 'doze', 'drag', 'draw', 'dream', 'drip', 'drop', 'drum',
    'duck', 'dull', 'dusk', 'dust', 'duty', 'each', 'eagle', 'earn', 'ease',
    'east', 'easy', 'edge', 'exit', 'face', 'fact', 'fade', 'fail', 'fair',
    'fake', 'fall', 'fame', 'farm', 'fast', 'fawn', 'fear', 'feed', 'feel',
    'fell', 'felt', 'fence', 'fern', 'field', 'file', 'fill', 'film', 'find',
    'fine', 'fire', 'firm', 'fish', 'five', 'flag', 'flame', 'flap', 'flat',
    'flaw', 'flew', 'flip', 'flow', 'foam', 'fold', 'folk', 'fond', 'food',
    'fool', 'foot', 'fork', 'form', 'fort', 'four', 'free', 'frog', 'from',
    'frost', 'fuel', 'full', 'fund', 'fuzz', 'gain', 'game', 'gate', 'gave',
    'gaze', 'gear', 'gift', 'give', 'glad', 'glass', 'globe', 'glow', 'glue',
    'goal', 'goat', 'gold', 'gone', 'good', 'gown', 'grab', 'grape', 'grass',
    'gray', 'green', 'grew', 'grid', 'grin', 'grip', 'grow', 'gulf', 'gust',
    'half', 'hall', 'halt', 'hand', 'happy', 'hare', 'harm', 'harp', 'heal',
    'heap', 'hear', 'heart', 'heat', 'heel', 'help', 'herb', 'herd', 'here',
    'hide', 'high', 'hike', 'hill', 'hint', 'hive', 'hold', 'hole', 'home',
    'honey', 'hood', 'hoof', 'hook', 'hope', 'horn', 'horse', 'hose', 'host',
    'hour', 'house', 'howl', 'hunt', 'hurt', 'idea', 'inch', 'iron', 'itch',
    'item', 'jail', 'jazz', 'join', 'joke', 'jolt', 'jump', 'jury', 'just',
    'keen', 'keep', 'kelp', 'kept', 'kick', 'kind', 'king', 'kiss', 'kite',
    'knee', 'knew', 'knife', 'knit', 'knob', 'knot', 'lace', 'lack', 'lake',
    'lamb', 'lamp', 'land', 'lane', 'lark', 'last', 'late', 'lawn', 'lazy',
    'lead', 'leaf', 'lean', 'leap', 'left', 'lemon', 'lend', 'lens', 'less',
    'life', 'lift', 'light', 'like', 'lime', 'line', 'link', 'lion', 'list',
    'live', 'load', 'loaf', 'loan', 'lock', 'loft', 'lone', 'long', 'look',
    'loop', 'lord', 'lose', 'loss', 'lost', 'loud', 'love', 'luck', 'lump',
    'lung', 'made', 'mail', 'main', 'make', 'male', 'mane', 'many', 'mare',
    'mark', 'mask', 'mast', 'math', 'maze', 'meal', 'mean', 'meat', 'melt',
    'mend', 'menu', 'mesh', 'mess', 'mild', 'mile', 'milk', 'mind', 'mine',
    'mint', 'miss', 'mist', 'moat', 'mode', 'mole', 'money', 'mood', 'moon',
    'more', 'moss', 'most', 'moth', 'mouse', 'move', 'much', 'mule', 'music',
    'must', 'mute', 'myth', 'nail', 'name', 'navy', 'near', 'neat', 'neck',
    'need', 'nest', 'news', 'next', 'nice', 'night', 'nine', 'none', 'noon',
    'nose', 'note', 'noun', 'oath', 'obey', 'once', 'onion', 'only', 'onto',
    'open', 'oval', 'oven', 'over', 'pace', 'pack', 'page', 'paid', 'pail',
    'pain', 'pair', 'pale', 'palm', 'paper', 'park', 'part', 'pass', 'past',
    'path', 'pave', 'peach', 'peak', 'peel', 'peer', 'pile', 'pill', 'pine',
    'pink', 'pipe', 'plan', 'plant', 'plate', 'play', 'plot', 'plow', 'plum',
    'plus', 'poem', 'poet', 'pole', 'pond', 'pony', 'pool', 'poor', 'porch',
    'pork', 'port', 'pose', 'post', 'pour', 'pray', 'prey', 'prop', 'pull',
    'pump', 'pure', 'push', 'queen', 'quick', 'quiz', 'race', 'rack', 'raft',
    'rail', 'rain', 'rake', 'rank', 'rare', 'rash', 'rate', 'read', 'real',
    'reap', 'rear', 'reed', 'reef', 'reel', 'rent', 'rest', 'rice', 'rich',
    'ride', 'rind', 'ring', 'ripe', 'rise', 'risk', 'river', 'road', 'roam',
    'roar', 'robe', 'rock', 'role', 'roll', 'roof', 'room', 'root', 'rope',
    'rose', 'ruby', 'rude', 'ruin', 'rule', 'rush', 'rust', 'safe', 'sage',
    'sail', 'salad', 'sale', 'salt', 'same', 'sand', 'sang', 'sank', 'save',
    'scan', 'scar', 'seal', 'seam', 'seat', 'seed', 'seek', 'seem', 'seen',
    'self', 'sell', 'send', 'sent', 'shark', 'sharp', 'shed', 'sheep',
    'shelf', 'shin', 'ship', 'shoe', 'shop', 'shore', 'shot', 'show', 'shut',
    'sick', 'side', 'sift', 'sign', 'silk', 'sing', 'sink', 'size', 'skid',
    'skim', 'skin', 'skip', 'slab', 'slam', 'slap', 'sled', 'sleep', 'slid',
    'slim', 'slip', 'slot', 'slow', 'smile', 'snake', 'snap', 'snip', 'snow',
    'snug', 'soak', 'soap', 'soar', 'sock', 'sofa', 'soft', 'soil', 'sold',
    'sole', 'some', 'song', 'soon', 'sore', 'sort', 'sound', 'soup', 'sour',
    'space', 'spin', 'spoon', 'spot', 'spun', 'stair', 'star', 'stem', 'step',
    'stew', 'stir', 'stone', 'stop', 'storm', 'story', 'straw', 'stub',
    'such', 'sugar', 'suit', 'sung', 'sure', 'surf', 'swam', 'swan', 'swap',
    'swim', 'sword', 'table', 'tail', 'tale', 'talk', 'tall', 'tame', 'tank',
    'tape', 'task', 'team', 'tear', 'tell', 'tend', 'tent', 'term', 'test',
    'than', 'that', 'thaw', 'them', 'then', 'they', 'thin', 'this', 'thus',
    'tick', 'tide', 'tidy', 'tiger', 'tile', 'till', 'tilt', 'time', 'tiny',
    'tire', 'toad', 'toast', 'told', 'toll', 'tomb', 'tone', 'took', 'tool',
    'tooth', 'torch', 'torn', 'toss', 'tour', 'town', 'trap', 'tray', 'tree',
    'trim', 'trip', 'trot', 'tuck', 'tune', 'turf', 'turn', 'twig', 'twin',
    'type', 'unit', 'upon', 'urge', 'vain', 'vane', 'vase', 'vast', 'veil',
    'vein', 'verb', 'very', 'vest', 'view', 'vine', 'visa', 'voice', 'vote',
    'wade', 'wage', 'wait', 'wake', 'walk', 'wall', 'wand', 'want', 'ward',
    'ware', 'warm', 'warn', 'wart', 'wash', 'wasp', 'water', 'wave', 'weak',
    'wear', 'weed', 'week', 'weep', 'well', 'went', 'were', 'west', 'whale',
    'what', 'wheel', 'when', 'whip', 'white', 'whom', 'wide', 'wife', 'wild',
    'will', 'wilt', 'wind', 'wine', 'wing', 'wink', 'wipe', 'wire', 'wise',
    'wish', 'with', 'wolf', 'wood', 'wool', 'word', 'wore', 'work', 'world',
    'worm', 'worn', 'wove', 'wrap', 'yard', 'yarn', 'yawn', 'year', 'yell',
    'yolk', 'your', 'zeal', 'zest', 'zinc', 'zone',
  ],
  // Tier 2 — five-to-seven letters, still common but more to scan.
  [
    'absorb', 'accent', 'access', 'advice', 'afford', 'agenda', 'almond',
    'amount', 'anchor', 'animal', 'ankle', 'answer', 'anthem', 'antler',
    'apron', 'archer', 'armour', 'aroma', 'arrive', 'artist', 'aspect',
    'assist', 'asthma', 'attend', 'attic', 'august', 'author', 'awake',
    'awful', 'bacon', 'badger', 'baker', 'bakery', 'bamboo', 'banana',
    'banner', 'barber', 'bargain', 'barley', 'barrel', 'basil', 'basin',
    'basket', 'batter', 'battle', 'beacon', 'beaver', 'beckon', 'bedding',
    'beetle', 'behave', 'bellow', 'belong', 'beside', 'better', 'beyond',
    'bishop', 'bitter', 'blazer', 'bleach', 'blister', 'boldly', 'bonnet',
    'border', 'borrow', 'bother', 'bottle', 'bounce', 'bracket', 'brains',
    'bramble', 'branch', 'brandy', 'breath', 'breeze', 'bridge', 'bridle',
    'bright', 'brittle', 'broken', 'bronze', 'brook', 'bubble', 'bucket',
    'buckle', 'budget', 'buffalo', 'builder', 'bundle', 'bunker', 'burden',
    'burrow', 'bushel', 'bustle', 'butter', 'button', 'cackle', 'cactus',
    'camel', 'camera', 'candid', 'candle', 'cannon', 'canoe', 'canvas',
    'canyon', 'carbon', 'career', 'carpet', 'carrot', 'cashew', 'castle',
    'casual', 'cavern', 'celery', 'cellar', 'cement', 'census', 'center',
    'cereal', 'chalk', 'chance', 'change', 'chapel', 'chapter', 'charge',
    'cheese', 'cherry', 'cherub', 'chicken', 'chilly', 'choice', 'chosen',
    'chrome', 'chuckle', 'circle', 'circus', 'civil', 'clamor', 'clever',
    'client', 'clinic', 'closet', 'clover', 'cluster', 'clutch', 'coast',
    'cobalt', 'coconut', 'coffee', 'collar', 'collect', 'column', 'comedy',
    'comfort', 'common', 'concert', 'consist', 'contest', 'convoy', 'copper',
    'corner', 'cortex', 'cotton', 'cousin', 'cradle', 'crater', 'crayon',
    'credit', 'cricket', 'crimson', 'crocus', 'crumble', 'crunch', 'culture',
    'custom', 'cymbal', 'damage', 'dampen', 'danger', 'dapper', 'dazzle',
    'debate', 'decade', 'decent', 'degree', 'delta', 'deputy', 'desert',
    'design', 'desire', 'dessert', 'detail', 'device', 'devote', 'diagram',
    'dilute', 'dimple', 'dinner', 'divide', 'docket', 'doctor', 'donkey',
    'doodle', 'double', 'dozen', 'dragon', 'dresser', 'drift', 'driver',
    'duffel', 'dugout', 'duplex', 'during', 'eager', 'earnest', 'easel',
    'effort', 'either', 'eleven', 'embark', 'ember', 'emblem', 'emerge',
    'empire', 'enable', 'engine', 'enrich', 'ensure', 'entire', 'equal',
    'escape', 'estate', 'ethics', 'event', 'evolve', 'exact', 'exile',
    'expand', 'expert', 'export', 'extend', 'fabric', 'falcon', 'fallow',
    'family', 'famous', 'fasten', 'father', 'fathom', 'feast', 'feather',
    'fellow', 'fender', 'fiddle', 'fierce', 'figure', 'filter', 'finger',
    'finish', 'flannel', 'flavor', 'fleece', 'flight', 'floral', 'flower',
    'flurry', 'flute', 'follow', 'fondue', 'forest', 'forget', 'formal',
    'former', 'fossil', 'foster', 'fourth', 'foyer', 'friend', 'frugal',
    'fumble', 'funnel', 'future', 'gadget', 'galaxy', 'gallon', 'gallop',
    'garage', 'garden', 'garlic', 'gather', 'gentle', 'gerbil', 'geyser',
    'giant', 'giggle', 'ginger', 'giraffe', 'glance', 'glitter', 'goblet',
    'goblin', 'golden', 'gopher', 'gospel', 'gossip', 'gourd', 'grace',
    'grader', 'grain', 'grand', 'grant', 'grasp', 'gravel', 'gravy', 'grocer',
    'ground', 'growth', 'guitar', 'gutter', 'habit', 'hammer', 'hamper',
    'handle', 'happen', 'harbor', 'hazard', 'header', 'health', 'hearth',
    'heaven', 'hedge', 'helmet', 'herald', 'hermit', 'heroic', 'hiccup',
    'hidden', 'hollow', 'honest', 'hornet', 'hotel', 'hubris', 'humble',
    'hunger', 'hurdle', 'hybrid', 'hyphen', 'icicle', 'ignite', 'immune',
    'impact', 'import', 'income', 'indeed', 'indigo', 'infant', 'inform',
    'insect', 'inside', 'invite', 'island', 'jacket', 'jaguar', 'jargon',
    'jigsaw', 'jingle', 'jockey', 'jungle', 'kennel', 'kernel', 'kettle',
    'kindle', 'kitten', 'knight', 'ladder', 'lagoon', 'lantern', 'lapel',
    'laptop', 'lately', 'lawyer', 'leader', 'legend', 'length', 'lentil',
    'lesson', 'letter', 'lettuce', 'level', 'lichen', 'likely', 'lilac',
    'limber', 'linger', 'litter', 'little', 'lively', 'lizard', 'lobby',
    'lobster', 'locket', 'locust', 'lodge', 'lonely', 'loyal', 'lumber',
    'luster', 'luxury', 'magnet', 'magpie', 'mallet', 'mammal', 'mango',
    'manner', 'mantis', 'mantle', 'marble', 'margin', 'marina', 'market',
    'marrow', 'marvel', 'mascot', 'matter', 'meadow', 'medal', 'medium',
    'mellow', 'melody', 'member', 'memory', 'mentor', 'merge', 'merit',
    'method', 'middle', 'mimic', 'mingle', 'minnow', 'minute', 'mirror',
    'mister', 'mitten', 'mixture', 'modern', 'modest', 'moment', 'monkey',
    'month', 'morsel', 'mosaic', 'mother', 'motion', 'motive', 'muffin',
    'murmur', 'museum', 'mustard', 'mutual', 'myself', 'napkin', 'narrow',
    'nation', 'nature', 'nectar', 'needle', 'nephew', 'nestle', 'nickel',
    'nimble', 'nobody', 'normal', 'notice', 'novel', 'nugget', 'number',
    'nurse', 'nutmeg', 'object', 'oblong', 'obtain', 'occupy', 'office',
    'omelet', 'openly', 'orange', 'orchid', 'ordeal', 'orient', 'origin',
    'osprey', 'ostrich', 'outfit', 'outlet', 'oxygen', 'oyster', 'paddle',
    'palace', 'pallet', 'pantry', 'papaya', 'parade', 'parcel', 'pardon',
    'parent', 'parlor', 'parrot', 'parsley', 'patrol', 'pauper', 'pebble',
    'pedal', 'pellet', 'pencil', 'people', 'pepper', 'perch', 'period',
    'permit', 'person', 'pewter', 'phrase', 'picnic', 'pigeon', 'pillar',
    'pillow', 'pilot', 'pincer', 'pirate', 'pistil', 'pistol', 'pitch',
    'planet', 'plaque', 'plasma', 'please', 'pledge', 'plenty', 'pliers',
    'plural', 'pocket', 'poetry', 'polish', 'pollen', 'ponder', 'poplar',
    'poppy', 'porous', 'portal', 'poster', 'potato', 'pottery', 'powder',
    'praise', 'prance', 'prefer', 'pretty', 'pretzel', 'prince', 'prism',
    'prompt', 'proper', 'proton', 'public', 'puddle', 'pulley', 'pulpit',
    'pumpkin', 'punish', 'pupil', 'puppet', 'purple', 'pursue', 'puzzle',
    'python', 'quartz', 'quench', 'quiver', 'rabbit', 'raccoon', 'radish',
    'rafter', 'ragged', 'raisin', 'rally', 'ramble', 'rancher', 'random',
    'rascal', 'rather', 'ratio', 'ravine', 'reason', 'recent', 'recipe',
    'reckon', 'record', 'reduce', 'reflex', 'refuge', 'region', 'relish',
    'remain', 'remedy', 'remind', 'remote', 'render', 'rental', 'repair',
    'repeat', 'report', 'rescue', 'resin', 'result', 'retain', 'return',
    'reveal', 'reward', 'rhubarb', 'ribbon', 'riddle', 'ripple', 'ritual',
    'robust', 'rocket', 'rodent', 'roster', 'rotate', 'rubber', 'rumble',
    'runner', 'runway', 'rustic', 'rustle', 'sacred', 'saddle', 'safari',
    'salmon', 'salute', 'sample', 'sandal', 'sapling', 'scarf', 'scenic',
    'school', 'scoop', 'scorch', 'scrap', 'screen', 'script', 'scroll',
    'sculpt', 'season', 'second', 'secret', 'sector', 'seldom', 'select',
    'senior', 'sensor', 'sermon', 'settle', 'severe', 'shadow', 'shampoo',
    'shatter', 'shelter', 'sheriff', 'shimmer', 'shovel', 'shower', 'shrimp',
    'shrine', 'signal', 'silent', 'silver', 'simple', 'singer', 'sister',
    'sizzle', 'sketch', 'slalom', 'sleeve', 'slogan', 'smooth', 'snooze',
    'soccer', 'social', 'socket', 'sodium', 'solemn', 'sonnet', 'sorrow',
    'speech', 'sphere', 'spider', 'spiral', 'spirit', 'splash', 'sponge',
    'spouse', 'spring', 'sprout', 'squash', 'squire', 'stable', 'stadium',
    'stanza', 'staple', 'statue', 'steady', 'stereo', 'sticky', 'stitch',
    'stormy', 'street', 'stride', 'stripe', 'stroll', 'strong', 'student',
    'studio', 'sturdy', 'subtle', 'suburb', 'sudden', 'summer', 'summit',
    'sunny', 'sunset', 'supper', 'survey', 'swivel', 'symbol', 'system',
    'tackle', 'tactic', 'talent', 'tangle', 'tassel', 'tavern', 'temper',
    'temple', 'tender', 'tennis', 'thicket', 'thimble', 'thirty', 'thistle',
    'thread', 'thrive', 'throne', 'ticket', 'timber', 'tissue', 'toffee',
    'tomato', 'tongue', 'trader', 'traffic', 'tragic', 'trance', 'travel',
    'treaty', 'tremor', 'trench', 'tribute', 'tricky', 'trolley', 'trophy',
    'trumpet', 'trust', 'tumble', 'tundra', 'tunnel', 'turkey', 'turnip',
    'turtle', 'twelve', 'twenty', 'twinkle', 'typical', 'umpire', 'unfold',
    'unique', 'unless', 'untidy', 'update', 'upward', 'urgent', 'useful',
    'usual', 'utmost', 'valley', 'vanish', 'vapor', 'vault', 'velvet',
    'vendor', 'verify', 'vessel', 'viable', 'violet', 'violin', 'visit',
    'visual', 'vivid', 'volume', 'voyage', 'waffle', 'wagon', 'walnut',
    'wander', 'weasel', 'weekly', 'whisper', 'wicker', 'widget', 'willow',
    'window', 'winner', 'winter', 'wisdom', 'wither', 'wizard', 'wombat',
    'wonder', 'wooden', 'worthy', 'wrench', 'yellow', 'yonder', 'zealous',
    'zenith', 'zipper', 'zither',
  ],
  // Tier 3 — longer words with spelling texture (doubles, silent letters,
  // ie/ei) where a plausible fake starts to really cost a beat.
  [
    'absolute', 'abundant', 'academic', 'accident', 'account', 'accuracy',
    'achieve', 'acoustic', 'acrobat', 'actually', 'address', 'adhesive',
    'adjacent', 'admirable', 'advance', 'advocate', 'affection', 'airport',
    'alligator', 'alphabet', 'already', 'although', 'altitude', 'ambition',
    'ancestor', 'ancient', 'announce', 'annoying', 'antelope', 'antique',
    'anxious', 'anywhere', 'apparent', 'appetite', 'applause', 'approach',
    'approval', 'aquarium', 'arrogant', 'article', 'assembly', 'asteroid',
    'athletic', 'attempt', 'attention', 'attitude', 'audience', 'autopilot',
    'autumn', 'avenue', 'avocado', 'backpack', 'backward', 'balance',
    'balcony', 'balloon', 'bandage', 'banister', 'barnacle', 'barrister',
    'bassoon', 'bearable', 'because', 'believe', 'between', 'bewilder',
    'bicycle', 'billiard', 'birthday', 'biscuit', 'blanket', 'blissful',
    'blizzard', 'blossom', 'bluebell', 'boundary', 'bracelet', 'breathe',
    'brochure', 'brought', 'buoyant', 'burglar', 'business', 'bustling',
    'cabbage', 'cabinet', 'calcium', 'calculate', 'calendar', 'campaign',
    'capacity', 'captain', 'capture', 'caravan', 'carnival', 'carousel',
    'carriage', 'cascade', 'casserole', 'cathedral', 'cattle', 'caution',
    'cautious', 'cedarwood', 'ceiling', 'centipede', 'century', 'ceramic',
    'certain', 'chamber', 'champion', 'channel', 'charity', 'charming',
    'checkers', 'chemical', 'chestnut', 'chimney', 'chivalry', 'chorus',
    'cinnamon', 'civilian', 'classical', 'climate', 'clockwise', 'coastal',
    'collapse', 'college', 'colossal', 'comedian', 'commence', 'company',
    'compass', 'compound', 'conclude', 'concrete', 'confetti', 'conquer',
    'constant', 'contrast', 'converse', 'corduroy', 'corridor', 'costume',
    'cottage', 'country', 'courage', 'courtesy', 'coverage', 'creature',
    'crescent', 'crystal', 'cucumber', 'cupboard', 'curious', 'curtain',
    'curvature', 'cushion', 'cylinder', 'daffodil', 'daughter', 'daydream',
    'dazzling', 'deadline', 'decision', 'decorate', 'delicate', 'delicious',
    'delight', 'delivery', 'descent', 'describe', 'designer', 'detailed',
    'devotion', 'diagonal', 'dialect', 'diameter', 'diamond', 'dinosaur',
    'diplomat', 'disciple', 'discover', 'disguise', 'dissolve', 'distance',
    'distinct', 'dividend', 'doctrine', 'doldrums', 'dolphin', 'domestic',
    'dominant', 'doorstep', 'doubtful', 'downhill', 'drawer', 'driftwood',
    'duration', 'dwelling', 'dynamite', 'earthly', 'eastern', 'eastward',
    'echoes', 'economy', 'educator', 'eggplant', 'eighteen', 'elaborate',
    'elegant', 'elephant', 'elevator', 'eloquent', 'embellish', 'emperor',
    'emphasis', 'employee', 'endless', 'engineer', 'enormous', 'entrance',
    'envelope', 'equation', 'escalate', 'especial', 'estimate', 'evening',
    'evidence', 'example', 'exchange', 'exercise', 'expanse', 'exposure',
    'exquisite', 'exterior', 'fantasy', 'farewell', 'fashion', 'feathery',
    'feature', 'festival', 'fiction', 'fifteen', 'fifteenth', 'firewood',
    'flamingo', 'flexible', 'florist', 'folklore', 'forecast', 'forehead',
    'foreign', 'fortress', 'fortune', 'fountain', 'fragile', 'fragrant',
    'freckle', 'freedom', 'frequent', 'friction', 'frontier', 'function',
    'furnace', 'furthest', 'galleon', 'gallery', 'gardener', 'gargoyle',
    'garment', 'gazette', 'general', 'generous', 'genuine', 'geometry',
    'glacier', 'glorious', 'graceful', 'gradient', 'graduate', 'grammar',
    'grandeur', 'grateful', 'gravity', 'grimace', 'guidance', 'gymnast',
    'handsome', 'harbour', 'hardware', 'harmonic', 'harvest', 'headline',
    'hedgehog', 'heirloom', 'heritage', 'herring', 'hesitate', 'hibernate',
    'highway', 'hilarious', 'historic', 'history', 'holiday', 'homemade',
    'horizon', 'hospital', 'humidity', 'hundred', 'hyacinth', 'icebound',
    'identity', 'illusion', 'imaginary', 'imagine', 'immense', 'imperial',
    'impulse', 'incident', 'indicate', 'industry', 'infinite', 'innocent',
    'inspire', 'instance', 'instant', 'interior', 'interval', 'intrepid',
    'inventor', 'irrigate', 'isolate', 'january', 'journey', 'jubilant',
    'junction', 'keepsake', 'keyboard', 'kindness', 'kingdom', 'kitchen',
    'laborious', 'landmark', 'laughter', 'lavender', 'leather', 'lecture',
    'leisure', 'liberty', 'library', 'lifetime', 'limerick', 'literacy',
    'luncheon', 'macaroni', 'machine', 'magnetic', 'mahogany', 'majestic',
    'mandolin', 'maritime', 'maximum', 'meanwhile', 'measure', 'medieval',
    'meridian', 'message', 'midnight', 'migrate', 'milestone', 'mineral',
    'miniature', 'minister', 'miracle', 'mischief', 'moderate', 'moisture',
    'molasses', 'molecule', 'momentum', 'monsoon', 'monster', 'monument',
    'morning', 'mosquito', 'movement', 'multiple', 'mushroom', 'musician',
    'mystery', 'mystical', 'narrator', 'national', 'natural', 'navigate',
    'neighbor', 'neither', 'nineteen', 'nocturne', 'northern', 'notebook',
    'nutrient', 'observe', 'october', 'octopus', 'offshore', 'operator',
    'opinion', 'opponent', 'opposite', 'optimism', 'orchard', 'ordinary',
    'organism', 'original', 'ornament', 'orthodox', 'outburst', 'outcome',
    'overcast', 'overcome', 'overlook', 'pamphlet', 'paradise', 'paragraph',
    'parakeet', 'particle', 'passenger', 'pastime', 'patience', 'pattern',
    'pavilion', 'pendulum', 'penguin', 'peninsula', 'perceive', 'perfume',
    'perimeter', 'personal', 'petition', 'pheasant', 'physical', 'picture',
    'pinnacle', 'pioneer', 'pipeline', 'platform', 'platinum', 'platypus',
    'pleasant', 'plentiful', 'politely', 'porridge', 'portrait', 'position',
    'positive', 'possible', 'practical', 'practice', 'precise', 'predict',
    'presence', 'preserve', 'pressure', 'previous', 'primrose', 'princess',
    'printer', 'priority', 'probable', 'problem', 'proceed', 'promise',
    'prosper', 'protect', 'provided', 'province', 'prudent', 'punctual',
    'purchase', 'pyramid', 'quarter', 'quarterly', 'radiance', 'rainbow',
    'rational', 'reaction', 'reassure', 'rebuild', 'receive', 'reckless',
    'recover', 'rectangle', 'regional', 'register', 'regular', 'reindeer',
    'relative', 'reliable', 'remember', 'renegade', 'require', 'research',
    'reserve', 'resident', 'resource', 'respect', 'response', 'reunion',
    'rhapsody', 'rhetoric', 'riverbed', 'romantic', 'rotation', 'roundup',
    'rucksack', 'sanctuary', 'sapphire', 'satchel', 'saturday', 'scaffold',
    'scenario', 'schedule', 'science', 'scramble', 'seasonal', 'seaweed',
    'sediment', 'sentence', 'sequence', 'serenade', 'seventeen', 'shepherd',
    'shoulder', 'signature', 'silently', 'skeleton', 'skirmish', 'smuggler',
    'solitude', 'solution', 'southern', 'spacious', 'special', 'spectrum',
    'splendid', 'sprinkle', 'squadron', 'standard', 'starling', 'sterling',
    'stomach', 'straddle', 'strange', 'strategy', 'structure', 'struggle',
    'stubborn', 'suitable', 'sunshine', 'surround', 'swifter', 'syllable',
    'symmetry', 'sympathy', 'synonym', 'tadpole', 'tangible', 'tapestry',
    'teaspoon', 'telegram', 'telescope', 'terrific', 'texture', 'theatre',
    'thirteen', 'thorough', 'thought', 'thousand', 'threshold', 'through',
    'thunder', 'together', 'tolerant', 'tonight', 'topsoil', 'tortoise',
    'tranquil', 'transfer', 'transit', 'treasure', 'treatment', 'tremble',
    'triangle', 'tribunal', 'triumph', 'tropical', 'trouble', 'turbine',
    'turquoise', 'tutorial', 'underdog', 'undergo', 'universe', 'unusual',
    'upstream', 'utensil', 'vacation', 'validate', 'vanguard', 'vanilla',
    'variety', 'velocity', 'vertical', 'veteran', 'vibrant', 'victory',
    'vigilant', 'village', 'vinegar', 'vintage', 'virtual', 'visible',
    'vocation', 'volcano', 'voyager', 'vulture', 'waistcoat', 'wanderer',
    'wardrobe', 'warranty', 'warrior', 'waterfall', 'weather', 'weekday',
    'weekend', 'weight', 'westward', 'whatever', 'whirlwind', 'whistle',
    'wholesome', 'wildlife', 'windmill', 'wingspan', 'wireless', 'wondrous',
    'woodland', 'yearling', 'yearning', 'yielding',
  ],
  // Tier 4 — long words and the classic traps.
  [
    'absolutely', 'accessible', 'accidentally', 'accomplish', 'accumulate',
    'achievement', 'acknowledge', 'acquaintance', 'adolescent',
    'advantageous', 'adventure', 'adversary', 'aeronautics', 'affectionate',
    'aggressive', 'agriculture', 'alliteration', 'ambassador', 'ambiguous',
    'ambitious', 'amphibian', 'anniversary', 'antibiotic', 'anticipate',
    'apostrophe', 'apparently', 'appearance', 'appreciate', 'apprentice',
    'appropriate', 'arbitrary', 'archipelago', 'architect', 'arithmetic',
    'artificial', 'assistance', 'associate', 'assortment', 'astonish',
    'astronomer', 'atmosphere', 'attendance', 'audacious', 'auditorium',
    'authentic', 'automatic', 'auxiliary', 'avalanche', 'bacteria',
    'beautiful', 'beginning', 'bewildered', 'bibliography', 'binoculars',
    'boisterous', 'boulevard', 'breakfast', 'brilliant', 'bureaucracy',
    'calculator', 'camouflage', 'candidate', 'candlestick', 'catastrophe',
    'caterpillar', 'celebrate', 'centennial', 'ceremony', 'certificate',
    'challenge', 'chandelier', 'changeable', 'character', 'charismatic',
    'chocolate', 'civilization', 'coincidence', 'collaborate', 'colleague',
    'colloquial', 'combination', 'commemorate', 'commercial', 'commitment',
    'committee', 'community', 'comparison', 'compassion', 'competitive',
    'completely', 'complexion', 'complicated', 'compliment', 'concentrate',
    'conscience', 'conscious', 'consequence', 'considerable', 'consonant',
    'conspicuous', 'contagious', 'contemporary', 'continuous', 'contradict',
    'controversy', 'convenience', 'conversation', 'cooperative', 'correspond',
    'courageous', 'courtyard', 'crystalline', 'curiosity', 'curriculum',
    'dangerous', 'declaration', 'dedication', 'definitely', 'deliberate',
    'delinquent', 'demonstrate', 'departure', 'dependable', 'description',
    'desperate', 'destination', 'deteriorate', 'determined', 'devastating',
    'dictionary', 'difference', 'difficulty', 'diligence', 'dimension',
    'direction', 'disappear', 'disappoint', 'discipline', 'discovery',
    'discrepancy', 'discussion', 'disposition', 'distinguish', 'distribute',
    'documentary', 'domination', 'duplicate', 'earthquake', 'eccentric',
    'education', 'efficiency', 'electricity', 'eliminate', 'embarrass',
    'emergency', 'emphasize', 'encourage', 'encyclopedia', 'endeavour',
    'enthusiasm', 'entrepreneur', 'environment', 'equilibrium', 'equipment',
    'equivalent', 'especially', 'essential', 'evaporate', 'exaggerate',
    'excellence', 'excellent', 'exceptional', 'exhausted', 'exhibition',
    'exhilarate', 'expedition', 'expensive', 'experience', 'experiment',
    'explanation', 'extinguish', 'extravagant', 'familiar', 'familiarity',
    'fascinating', 'favourite', 'february', 'fictitious', 'frequently',
    'furniture', 'generosity', 'gigantic', 'government', 'gratitude',
    'grievance', 'guarantee', 'gymnasium', 'handkerchief', 'happened',
    'harmonious', 'headquarters', 'hemisphere', 'hereditary', 'hesitation',
    'hippopotamus', 'horizontal', 'hospitality', 'humanitarian', 'humorous',
    'hurricane', 'hypothesis', 'identical', 'ignorance', 'illuminate',
    'illustrate', 'imagination', 'immaculate', 'immediately', 'impeccable',
    'implement', 'important', 'impossible', 'impression', 'inaccurate',
    'incredible', 'independence', 'independent', 'individual', 'inevitable',
    'influence', 'influential', 'ingenious', 'ingredient', 'inheritance',
    'initiative', 'innovation', 'inquisitive', 'inspiration', 'instrument',
    'intelligence', 'interesting', 'intermediate', 'interpret', 'interrupt',
    'introduction', 'invisible', 'invitation', 'irresistible', 'kaleidoscope',
    'kilometre', 'knowledge', 'laboratory', 'labyrinth', 'landscape',
    'language', 'legendary', 'legislature', 'lieutenant', 'lightning',
    'limitation', 'literature', 'magnificent', 'maintenance', 'manoeuvre',
    'manuscript', 'marvellous', 'masquerade', 'mathematics', 'mayonnaise',
    'mechanical', 'medallion', 'melancholy', 'memorandum', 'metaphor',
    'metropolis', 'millennium', 'mischievous', 'monotonous', 'mountain',
    'muscle', 'mysterious', 'necessary', 'negotiate', 'neighbour',
    'nevertheless', 'noticeable', 'numerator', 'obedience', 'obedient',
    'obligation', 'observation', 'obstacle', 'occasion', 'occasionally',
    'occurred', 'occurrence', 'opportunity', 'opposition', 'orchestra',
    'outrageous', 'overwhelm', 'parachute', 'parallel', 'paralysis',
    'parliament', 'participate', 'particular', 'peculiar', 'perception',
    'performance', 'permanent', 'permission', 'perseverance', 'personality',
    'personally', 'perspective', 'persuade', 'persuasion', 'phenomenal',
    'photograph', 'physician', 'picturesque', 'playwright', 'pneumonia',
    'porcelain', 'possession', 'practically', 'precious', 'preferable',
    'prehistoric', 'preparation', 'prescription', 'presentation', 'president',
    'prestigious', 'presumably', 'privilege', 'procedure', 'proclamation',
    'professional', 'projection', 'pronounce', 'proportion', 'prosperity',
    'protagonist', 'provisional', 'psychology', 'publication', 'punctuation',
    'quantity', 'question', 'recognizable', 'recommend', 'rectangular',
    'refreshment', 'rehearsal', 'relationship', 'reluctant', 'remarkable',
    'reminiscent', 'renaissance', 'repetition', 'reputation', 'resemblance',
    'reservation', 'reservoir', 'resilient', 'resolution', 'resourceful',
    'respectable', 'responsible', 'restaurant', 'rhinoceros', 'rhythm',
    'ridiculous', 'sandwich', 'satellite', 'satisfaction', 'scarecrow',
    'scholarship', 'scissors', 'scrumptious', 'secondary', 'sentimental',
    'separate', 'significance', 'silhouette', 'simultaneous', 'sincere',
    'sincerely', 'skyscraper', 'solidarity', 'sophomore', 'souvenir',
    'spaghetti', 'spectacular', 'spontaneous', 'stationery', 'strength',
    'strenuous', 'subscription', 'substantial', 'successful', 'sufficient',
    'suggestion', 'supernatural', 'superstition', 'surprise', 'surveillance',
    'suspicious', 'sustainable', 'symbolize', 'symphony', 'synchronize',
    'temperament', 'temperature', 'temporarily', 'tentative', 'terrestrial',
    'territory', 'thermometer', 'thesaurus', 'tomorrow', 'tournament',
    'translation', 'transparent', 'treacherous', 'tremendous', 'turbulence',
    'twilight', 'typewriter', 'umbrella', 'unanimous', 'unbelievable',
    'uncertainty', 'underneath', 'understand', 'undoubtedly', 'unfamiliar',
    'unfortunate', 'university', 'vaccination', 'vacuum', 'vegetable',
    'vegetarian', 'versatile', 'veterinary', 'vocabulary', 'voluntary',
    'vulnerable', 'watermelon', 'wednesday', 'wheelbarrow', 'wilderness',
    'willingness', 'withdrawal', 'xylophone', 'yesterday',
  ],
];

/**
 * Common English words that are NOT in the shipped tiers but that a one-edit
 * mutation could accidentally form ("two" -> "tow", "form" -> "from"). A fake
 * that lands on any of these would punish a correct read, so the generator
 * rejects against VALID ∪ this guard, not VALID alone.
 */
const COMMON_GUARD = [
  'a', 'an', 'as', 'at', 'be', 'by', 'do', 'go', 'he', 'if', 'in', 'is',
  'it', 'me', 'my', 'no', 'of', 'on', 'or', 'so', 'to', 'up', 'us', 'we',
  'act', 'add', 'age', 'ago', 'aid', 'aim', 'air', 'all', 'and', 'ant',
  'any', 'ape', 'apt', 'arc', 'are', 'art', 'ate', 'axe', 'bad', 'bag',
  'ban', 'bar', 'bat', 'bay', 'bee', 'beg', 'bet', 'bid', 'bin', 'bit',
  'boa', 'bog', 'bow', 'boy', 'bud', 'bug', 'bun', 'but', 'buy', 'cab',
  'can', 'cap', 'cod', 'cog', 'con', 'cop', 'cot', 'cow', 'coy', 'cry',
  'cub', 'cue', 'cut', 'dam', 'den', 'dew', 'did', 'die', 'dig', 'dim',
  'din', 'dip', 'doe', 'dot', 'dip', 'due', 'dug', 'dun', 'dye', 'ear',
  'eel', 'ebb', 'eid', 'eke', 'elf', 'elk', 'elm', 'era', 'eve', 'eye', 'fan',
  'far', 'fat', 'fax', 'fed', 'fee', 'few', 'fig', 'fin', 'fit', 'fix',
  'flu', 'fly', 'foe', 'fog', 'for', 'fox', 'fry', 'gap', 'gas', 'gel',
  'gem', 'get', 'gig', 'gin', 'got', 'gum', 'gun', 'gut', 'guy', 'gym',
  'had', 'ham', 'has', 'hay', 'hen', 'her', 'hew', 'hey', 'hid', 'him',
  'hip', 'his', 'hit', 'hoe', 'hog', 'hop', 'how', 'hub', 'hue', 'hug',
  'hum', 'hut', 'ill', 'imp', 'ink', 'inn', 'ion', 'ire', 'irk', 'its',
  'ivy', 'jab', 'jam', 'jar', 'jaw', 'jay', 'jet', 'jig', 'jog', 'jot',
  'joy', 'jug', 'keg', 'kid', 'kin', 'kit', 'lab', 'lad', 'lag', 'lap',
  'law', 'lay', 'lea', 'led', 'lee', 'let', 'lid', 'lie', 'lip', 'lit',
  'lob', 'log', 'lot', 'low', 'mad', 'man', 'mat', 'maw', 'may', 'men',
  'met', 'mid', 'mix', 'mob', 'mop', 'mow', 'mud', 'mug', 'nab', 'nag',
  'nap', 'net', 'nub', 'net', 'nil', 'nip', 'nit', 'nod', 'nor', 'not',
  'now', 'nun', 'nut', 'oak', 'oar', 'oat', 'odd', 'ode', 'off', 'oft',
  'oil', 'one', 'opt', 'orb', 'ore', 'our', 'out', 'owe', 'owl', 'own',
  'pad', 'pal', 'pan', 'par', 'pat', 'paw', 'pay', 'pea', 'peg', 'pet',
  'pie', 'pig', 'pin', 'pit', 'ply', 'pod', 'pop', 'pot', 'pro', 'pry',
  'pub', 'pun', 'pup', 'put', 'rag', 'ram', 'ran', 'rap', 'rat', 'raw',
  'ray', 'rib', 'rid', 'rig', 'rim', 'rip', 'rob', 'rod', 'roe', 'rot',
  'row', 'rub', 'rue', 'rug', 'rum', 'rut', 'rye', 'sad', 'sag', 'sap',
  'sat', 'saw', 'say', 'set', 'sew', 'she', 'shy', 'sin', 'sip', 'sir',
  'ski', 'sly', 'sob', 'sod', 'son', 'sow', 'soy', 'spa', 'spy', 'sty',
  'sub', 'sue', 'sum', 'tab', 'tag', 'tan', 'tap', 'tar', 'tax', 'the',
  'thy', 'tie', 'tin', 'tip', 'toe', 'ton', 'too', 'tot', 'tow', 'toy',
  'try', 'tub', 'tug', 'two', 'urn', 'use', 'van', 'vat', 'vet', 'via',
  'vie', 'vow', 'wag', 'war', 'was', 'wax', 'way', 'web', 'wed', 'wee',
  'who', 'why', 'wig', 'wit', 'woe', 'won', 'woo', 'wry', 'yak', 'yam',
  'yap', 'yaw', 'yet', 'yew', 'you', 'zap', 'zoo',
  'ability', 'able', 'about', 'above', 'accept', 'across', 'action',
  'after', 'again', 'agree', 'ahead', 'alive', 'alone', 'along', 'also',
  'always', 'among', 'angle', 'anger', 'angry', 'answer', 'apple', 'area',
  'argue', 'arrow', 'aside', 'attack', 'aunt', 'autumn', 'awake', 'away',
  'back', 'ball', 'band', 'bank', 'base', 'bath', 'beach', 'bean', 'beat',
  'been', 'beer', 'bell', 'belt', 'bend', 'best', 'bird', 'bite', 'black',
  'blade', 'blame', 'blank', 'blind', 'block', 'blood', 'blow', 'blue',
  'board', 'boat', 'body', 'boil', 'bold', 'bone', 'book', 'boot', 'born',
  'boss', 'both', 'bowl', 'brain', 'brand', 'brave', 'break', 'brick',
  'bring', 'broad', 'broke', 'brown', 'brush', 'build', 'burn', 'burst',
  'busy', 'cake', 'call', 'calm', 'came', 'camp', 'card', 'care', 'cart',
  'case', 'cash', 'cast', 'cave', 'cell', 'cent', 'chain', 'chalk',
  'charm', 'chart', 'chase', 'cheap', 'check', 'cheese', 'chest', 'chief',
  'child', 'chin', 'chip', 'choice', 'city', 'claim', 'class', 'clay',
  'clean', 'clear', 'climb', 'cling', 'close', 'cloth', 'club', 'coach',
  'coal', 'coast', 'coat', 'code', 'cold', 'come', 'cook', 'cool', 'cope',
  'copy', 'cord', 'core', 'corn', 'cost', 'count', 'court', 'cover',
  'crack', 'craft', 'crash', 'cream', 'crew', 'crime', 'crop', 'cross',
  'crowd', 'crown', 'cure', 'curl', 'curve', 'dare', 'dark', 'data',
  'date', 'dawn', 'dead', 'deal', 'dear', 'debt', 'deck', 'deep', 'deer',
  'depth', 'dirt', 'dish', 'dive', 'done', 'doubt', 'down', 'dozen',
  'draft', 'drag', 'drain', 'draw', 'dress', 'drew', 'drift', 'drink',
  'drive', 'drop', 'drum', 'duck', 'dull', 'dust', 'duty', 'each',
  'early', 'earn', 'earth', 'ease', 'east', 'easy', 'edge', 'eight',
  'either', 'else', 'empty', 'enemy', 'enjoy', 'enter', 'equal', 'even',
  'event', 'ever', 'every', 'exact', 'exit', 'extra', 'face', 'fact',
  'fade', 'fail', 'fair', 'faith', 'fall', 'false', 'fame', 'farm',
  'fate', 'fault', 'fear', 'feed', 'feel', 'fell', 'felt', 'fence',
  'field', 'fifth', 'fight', 'file', 'fill', 'film', 'final', 'find',
  'fine', 'firm', 'first', 'five', 'flag', 'flame', 'flash', 'flat',
  'flesh', 'float', 'flood', 'floor', 'flow', 'fold', 'folk', 'food',
  'foot', 'force', 'fork', 'form', 'fort', 'forth', 'found', 'four',
  'frame', 'free', 'fresh', 'from', 'front', 'frost', 'fruit', 'fuel',
  'full', 'fund', 'gain', 'gate', 'gave', 'gear', 'gift', 'girl', 'give',
  'glad', 'globe', 'glory', 'glove', 'glow', 'goal', 'goat', 'gone',
  'good', 'grace', 'grade', 'grain', 'grand', 'grant', 'grass', 'grave',
  'gray', 'great', 'grew', 'grey', 'grip', 'group', 'grow', 'guard',
  'guess', 'guest', 'guide', 'hair', 'half', 'hall', 'halt', 'hang',
  'hard', 'harm', 'have', 'head', 'heal', 'heap', 'hear', 'heart', 'heat',
  'heavy', 'heel', 'held', 'hell', 'help', 'here', 'hero', 'hide', 'high',
  'hill', 'hint', 'hire', 'hold', 'hole', 'holy', 'home', 'honey', 'hook',
  'hope', 'horn', 'horse', 'host', 'hour', 'huge', 'hunt', 'hurt', 'idea',
  'inch', 'into', 'iron', 'item', 'join', 'joint', 'joke', 'judge',
  'juice', 'just', 'keen', 'keep', 'kept', 'kick', 'kill', 'kind', 'knee',
  'knew', 'knife', 'knock', 'known', 'lace', 'lack', 'lady', 'laid',
  'lake', 'land', 'lane', 'large', 'last', 'late', 'laugh', 'lawn',
  'lead', 'lean', 'leap', 'learn', 'least', 'leave', 'left', 'lend',
  'less', 'level', 'lift', 'like', 'limb', 'limit', 'line', 'link',
  'lion', 'list', 'live', 'load', 'loaf', 'loan', 'local', 'lock',
  'lodge', 'lone', 'long', 'look', 'loop', 'loose', 'lord', 'lose',
  'loss', 'lost', 'loud', 'love', 'luck', 'lunch', 'lung', 'made', 'mail',
  'main', 'make', 'male', 'many', 'march', 'mark', 'mass', 'match',
  'mate', 'math', 'meal', 'mean', 'meat', 'meet', 'melt', 'mend', 'mere',
  'mess', 'might', 'mild', 'mile', 'mill', 'mind', 'mine', 'miss', 'mist',
  'mode', 'more', 'most', 'moth', 'mount', 'mouse', 'mouth', 'move',
  'much', 'must', 'nail', 'name', 'near', 'neat', 'neck', 'need', 'nest',
  'news', 'next', 'nice', 'nine', 'noble', 'noise', 'none', 'noon',
  'north', 'nose', 'note', 'noun', 'nurse', 'obey', 'ocean', 'offer',
  'often', 'once', 'only', 'onto', 'open', 'order', 'other', 'ought',
  'ounce', 'oven', 'over', 'pace', 'pack', 'page', 'paid', 'pain',
  'paint', 'pair', 'pale', 'palm', 'pant', 'park', 'part', 'pass',
  'past', 'path', 'peace', 'peak', 'pearl', 'pick', 'piece', 'pile',
  'pine', 'pink', 'pipe', 'pitch', 'place', 'plain', 'plan', 'plate',
  'play', 'plot', 'poem', 'point', 'pole', 'pond', 'pool', 'poor',
  'port', 'pose', 'post', 'pour', 'power', 'press', 'price', 'pride',
  'prime', 'print', 'prize', 'proof', 'proud', 'prove', 'pull', 'pump',
  'pure', 'push', 'quit', 'quite', 'race', 'rack', 'rage', 'raise',
  'range', 'rank', 'rapid', 'rare', 'rate', 'reach', 'read', 'ready',
  'real', 'rear', 'rent', 'rest', 'rice', 'rich', 'ride', 'rise', 'risk',
  'roar', 'roast', 'roll', 'roof', 'room', 'root', 'rope', 'rose',
  'rough', 'round', 'route', 'royal', 'rude', 'rule', 'rush', 'rust',
  'safe', 'sail', 'sake', 'sale', 'salt', 'same', 'save', 'scale',
  'scare', 'scene', 'scope', 'score', 'seal', 'seat', 'seed', 'seek',
  'seem', 'seen', 'self', 'sell', 'send', 'sense', 'sent', 'serve',
  'seven', 'shade', 'shake', 'shall', 'shame', 'shape', 'share', 'shed',
  'sheep', 'sheet', 'shelf', 'shell', 'shift', 'shine', 'shirt', 'shock',
  'shoe', 'shook', 'shoot', 'shop', 'shore', 'short', 'shot', 'shout',
  'show', 'shut', 'sick', 'side', 'sigh', 'sight', 'sign', 'silk',
  'since', 'sing', 'sink', 'site', 'size', 'skill', 'skin', 'skirt',
  'slave', 'slid', 'slide', 'slip', 'slope', 'slow', 'small', 'smart',
  'smell', 'smoke', 'snake', 'soap', 'sock', 'soft', 'soil', 'sold',
  'sole', 'solid', 'solve', 'some', 'soon', 'sore', 'sorry', 'sort',
  'soul', 'south', 'speak', 'speed', 'spell', 'spend', 'spent', 'spin',
  'spite', 'split', 'spoke', 'sport', 'spot', 'spray', 'spread', 'stab',
  'staff', 'stage', 'stair', 'stake', 'stamp', 'stand', 'stare', 'start',
  'state', 'stay', 'steal', 'steam', 'steel', 'steep', 'steer', 'stem',
  'step', 'stick', 'stiff', 'still', 'stock', 'stole', 'stone', 'stood',
  'stop', 'store', 'storm', 'stove', 'strap', 'straw', 'strip', 'stuck',
  'study', 'stuff', 'style', 'such', 'suit', 'sure', 'sweep', 'sweet',
  'swim', 'swing', 'sword', 'take', 'tale', 'talk', 'tall', 'tank',
  'tape', 'task', 'taste', 'teach', 'team', 'tear', 'tell', 'tend',
  'tent', 'term', 'test', 'text', 'than', 'that', 'them', 'then', 'there',
  'these', 'they', 'thick', 'thin', 'thing', 'think', 'third', 'this',
  'those', 'three', 'threw', 'throw', 'thumb', 'thus', 'tide', 'tidy',
  'tight', 'till', 'tilt', 'tiny', 'tire', 'title', 'today', 'told',
  'tone', 'tool', 'tooth', 'total', 'touch', 'tough', 'tour', 'toward',
  'tower', 'town', 'trace', 'track', 'trade', 'trail', 'train', 'trap',
  'tray', 'treat', 'trend', 'trial', 'tribe', 'trick', 'trim', 'trip',
  'truck', 'true', 'trunk', 'trust', 'truth', 'tube', 'tune', 'turn',
  'twin', 'twist', 'type', 'uncle', 'under', 'union', 'unit', 'until',
  'upon', 'upper', 'urge', 'used', 'user', 'usual', 'value', 'verb',
  'verse', 'very', 'view', 'visit', 'vital', 'vote', 'wage', 'wait',
  'wake', 'walk', 'want', 'ward', 'warm', 'warn', 'wash', 'waste',
  'watch', 'wear', 'week', 'well', 'went', 'were', 'west', 'what',
  'wheat', 'wheel', 'when', 'where', 'which', 'while', 'whip', 'whole',
  'whom', 'whose', 'wide', 'wife', 'wild', 'will', 'wine', 'wing',
  'wipe', 'wire', 'wise', 'wish', 'with', 'woke', 'woman', 'wood',
  'wool', 'wore', 'work', 'worm', 'worn', 'worry', 'worse', 'worst',
  'worth', 'would', 'wound', 'wrap', 'wrist', 'write', 'wrong', 'wrote',
  'yard', 'yarn', 'year', 'yell', 'young', 'your', 'youth', 'zero',
  'zone',
];

/** Every shipped, playable word. Order: tier by tier, list order. */
export const ALL_WORDS = TIERS.flat();

/** Validity set for gameplay: the shipped tiers. */
const VALID = new Set(ALL_WORDS);

/** Rejection set for the fake generator: shipped words ∪ common guard. */
const GUARD = new Set([...ALL_WORDS, ...COMMON_GUARD, ...EXTENDED_GUARD]);

/**
 * The validity checker the acceptance gate names: a real (shipped) word must
 * NEVER be rejected. Case- and whitespace-forgiving so no UI plumbing can
 * manufacture a false negative.
 */
export function isValidWord(word) {
  return VALID.has(String(word ?? '').trim().toLowerCase());
}

export function tierCount() { return TIERS.length; }

/** Words available at a tier (clamped, so a too-high tier never throws). */
export function tierWords(tier) {
  const t = Math.max(0, Math.min(TIERS.length - 1, tier | 0));
  return TIERS[t];
}

/** Deterministically pick one real word from a tier. */
export function pickWord(tier, rand) {
  const words = tierWords(tier);
  return words[Math.floor(rand() * words.length) % words.length];
}

const gcd = (a, b) => (b === 0 ? a : gcd(b, a % b));

/**
 * The no-repeat draw (Phase 9): the k-th word of a seeded coprime walk
 * through a tier. `rand` must be a FRESH rng seeded per (run, tier) — two
 * draws fix the walk's offset and stride — so for a given lane every k maps
 * to a distinct word until the whole tier cycles (940-2,200 words: longer
 * than any run's stay in a tier). Kills both back-to-back duplicates and
 * the birthday-problem repeats a uniform draw guarantees.
 */
export function pickWordCycle(tier, k, rand) {
  const words = tierWords(tier);
  const n = words.length;
  const offset = Math.floor(rand() * n) % n;
  let stride = 1 + (Math.floor(rand() * (n - 1)) % (n - 1));
  while (gcd(stride, n) !== 1) stride = (stride % (n - 1)) + 1;
  return words[(offset + (k % n) * stride) % n];
}

const VOWELS = 'aeiou';

/** The mutation strategies, all one honest "misread" away from the source. */
const MUTATIONS = [
  // Swap two adjacent letters: recieve.
  (w, i) => (i < w.length - 1 && w[i] !== w[i + 1]
    ? w.slice(0, i) + w[i + 1] + w[i] + w.slice(i + 2) : null),
  // Double a letter: dinnner without the drama — winnter.
  (w, i) => w.slice(0, i + 1) + w[i] + w.slice(i + 1),
  // Drop a letter (never below 3 chars): begining.
  (w, i) => (w.length > 3 ? w.slice(0, i) + w.slice(i + 1) : null),
  // Substitute a vowel with a different vowel: definately.
  (w, i) => {
    const c = w[i];
    if (!VOWELS.includes(c)) return null;
    const alt = VOWELS[(VOWELS.indexOf(c) + 1 + Math.floor(i / 2)) % VOWELS.length];
    return alt === c ? null : w.slice(0, i) + alt + w.slice(i + 1);
  },
];

/**
 * Build a plausible misspelling of `word` — guaranteed to differ from the
 * source and to NOT be a recognized word (shipped list or common guard), so a
 * player who reads correctly is never punished for our generator's luck.
 *
 * Deterministic for a given (word, rand-stream). Termination is guaranteed:
 * after bounded random attempts it sweeps every mutation × position, and a
 * finite guard set cannot absorb every single-edit variant of a word.
 */
export function makeFake(word, rand) {
  const w = String(word).toLowerCase();
  const bad = (f) => !f || f === w || GUARD.has(f);

  for (let attempt = 0; attempt < 24; attempt++) {
    const m = MUTATIONS[Math.floor(rand() * MUTATIONS.length) % MUTATIONS.length];
    const i = Math.floor(rand() * w.length) % w.length;
    const f = m(w, i);
    if (!bad(f)) return f;
  }
  // Deterministic sweep — rand no longer consulted.
  for (const m of MUTATIONS) {
    for (let i = 0; i < w.length; i++) {
      const f = m(w, i);
      if (!bad(f)) return f;
    }
  }
  // Last resort: substitute each position with each letter until unrecognized.
  for (let i = w.length - 1; i >= 0; i--) {
    for (const c of 'zxqjkvw') {
      if (w[i] === c) continue;
      const f = w.slice(0, i) + c + w.slice(i + 1);
      if (!bad(f)) return f;
    }
  }
  return w + 'x'; // unreachable in practice; still not a guard word
}
